export const translations = {
  en: {
    // Welcome Screen
    welcome_title: "PROJECT ZERO TOOL",
    welcome_subtitle: "Fully client-side configuration tool for DayZ Expansion. Directly modify, validate, and manage server configs and maps locally inside your browser.",
    welcome_restore_btn: "📂 RESTORE ACCESS TO: {folder}",
    welcome_open_btn: "📂 OPEN SERVER CONFIG DIRECTORY",
    welcome_open_diff_btn: "OPEN A DIFFERENT FOLDER",
    welcome_browser_warn_title: "⚠️ BROWSER NOT SUPPORTED",
    welcome_browser_warn_body: "Your current browser does not support the File System Access API. Please switch to a Chromium-based desktop browser (e.g. Google Chrome, Microsoft Edge, Opera, or Brave) to select and edit local server directories.",
    welcome_expected_struct: "EXPECTED FOLDER STRUCTURE:",
    welcome_expected_desc: "Open the DayZ server profiles folder containing:",

    // Header & Tabs
    header_station: "EXPANSION // CONFIG_STATION",
    header_control_center: "PROJECT ZERO TOOL",
    header_dir: "DIR:",
    header_disconnect: "× DISCONNECT",
    tab_dashboard: "Dashboard",
    tab_economy: "Economy",
    tab_quests: "Quests",
    tab_aibots: "AI Bots",
    tab_settings: "Settings",
    tab_map: "Interactive Map",
    tab_raw_editor: "JSON",
    header_unsaved: "UNSAVED",
    header_export_package: "💾 EXPORT PACKAGE",
    header_discard: "DISCARD",
    header_reload: "↻ RELOAD",
    header_shortcuts: "Keyboard shortcuts",
    all_saved: "✓ All saved",
    select_all: "Select all",
    select_none: "Select none",

    // Dashboard Tabs
    dash_sub_status: "SYSTEM STATUS",
    dash_sub_changelog: "SESSION CHANGELOG",
    dash_sub_backups: "BACKUP EXPLORER",

    // Dashboard HUD Cards
    hud_quests: "Quests Configured",
    hud_npcs: "Active NPCs",
    hud_market: "Market Database",
    hud_patrols: "AI Patrol Routes",
    hud_safezones: "Green / Safe Zones",
    hud_total_configs: "Total Configurations",

    // Dashboard Status Panel
    status_pending_title: "// PENDING_UNSAVED_CHANGES",
    status_package_title: "PACKAGE STATUS",
    status_match_disk: "ALL CONFIGURATION FILES MATCH LOCAL DISK DATA",
    status_size: "SIZE:",
    status_modified: "MODIFIED",
    status_save_btn: "SAVE",
    status_revert_btn: "REVERT",

    // Dashboard Healing Panel
    status_diagnostics_title: "// AUTO_FIX_DIAGNOSTICS",
    status_healing_title: "VALIDATION & HEALING",
    status_fix_all_btn: "🛠 AUTO-FIX ALL ISSUES",
    status_healthy: "SYSTEM HEALTHY: NO STRUCTURAL OR SYNTAX ISSUES DETECTED",
    status_repair_syntax: "REPAIR SYNTAX",
    status_heal_btn: "HEAL",

    // Dashboard Database Panel
    db_title: "// SERVER_ITEM_DATABASE",
    db_header: "SERVER ITEMS DATABASE (TYPES.XML)",
    db_clear_btn: "CLEAR DATABASE",
    db_desc: "Upload your DayZ server's types.xml file (containing vanilla and modded item definitions) to populate the autocomplete suggestions list across all editors (Market categories, Loadout designer, Trader overrides, and Quest objectives).",
    db_choose_btn: "📁 CHOOSE TYPES.XML FILE",
    db_active_db: "✓ Active Database: {count} items loaded and ready.",
    db_no_db: "No database loaded. Only scanned local files are used for autocomplete.",

    // Dashboard Console
    console_title: "CONSOLE LOGS",
    console_init_ok: "[SYSTEM INITIALIZATION] OK · Loaded {count} configs.",
    console_diagnostics_active: "[DIAGNOSTICS SERVICE] Inferred schemas mapped. Auditing active...",
    console_warn_issues: "[DIAGNOSTICS] Warning: Found {syntax} syntax errors and {struct} structural warnings. Click \"AUTO-FIX\" to repair.",
    console_status_green: "[DIAGNOSTICS] System status green: 0 syntax issues, 0 schema mismatches.",

    // Dashboard Changelog
    change_title: "// SESSION_MUTATIONS_AUDIT",
    change_header: "UNSAVED FIELD-LEVEL CHANGELOG",
    change_desc: "This tab displays individual property mutations that currently exist only in memory. You can revert single changes to their disk state using the \"Undo\" button.",
    change_no_changes: "NO UNSAVED MODIFICATIONS IN THE CURRENT SESSION",
    change_th_path: "FIELD PATH",
    change_th_orig: "ORIGINAL VALUE",
    change_th_mod: "MODIFIED VALUE",
    change_th_action: "ACTION",
    change_undo: "Undo",

    // Dashboard Backups
    backup_title: "// BACKUP_ARCHIVE_EXPLORER",
    backup_header: "BACKUP EXPLORER",
    backup_desc: "Restore previous versions of configurations in one click. Restores overwrite active files on disk and prompt confirmation.",
    backup_refresh: "↻ REFRESH",
    backup_refreshing: "REFRESHING...",
    backup_loading: "RETRIEVING BACKUPS FROM DISK...",
    backup_no_points: "NO RESTORE POINTS FOUND IN BACKUPS DIRECTORY",
    backup_full: "FULL PACKAGE",
    backup_single: "SINGLE FILE",
    backup_files_in_archive: "Files in archive: {count}",
    backup_show_files: "▶ SHOW FILES LIST",
    backup_hide_files: "▼ HIDE FILES LIST",
    backup_restore_btn: "📂 RESTORE",

    // Modals
    modal_confirm_restore_title: "RESTORE BACKUP",
    modal_confirm_restore_body: "Are you sure you want to restore \"{backup}\"?\n\nThis will overwrite all active files on disk with the files from this backup.\n\nAny unsaved changes currently in memory will be lost.",
    modal_confirm_discard_title: "DISCARD ALL CHANGES",
    modal_confirm_discard_body: "This will revert ALL unsaved modifications in memory back to the last saved state on disk.\n\nThis action cannot be undone.",
    modal_confirm_discard_btn: "DISCARD ALL",
    modal_confirm_cancel: "CANCEL",

    // Map Sidebar
    map_grid_presets: "// GRID_PRESETS",
    map_custom_size_label: "MAP WIDTH (METERS):",
    map_custom_size_opt: "Custom Size...",
    map_measure_btn: "MEASURE DISTANCE",
    map_measure_on: "MEASURE: ON",
    map_load_custom: "🗺️ LOAD CUSTOM MAP",
    map_merge_patrol_route: "MERGE PATROL ROUTE",
    map_merge_with: "Merge with",
    map_merge_btn: "MERGE",
    map_double_click_spawn: "DOUBLE CLICK: SPAWN ENTITY",
    map_inspect_selected: "INSPECT SELECTED",
    map_location_enabled: "Location Enabled",
    map_more_settings: "MORE SETTINGS",
    map_hovered_entity: "HOVERED ENTITY (CLICK TO SELECT)",
    map_spawn_new_entity: "SPAWN NEW ENTITY",
    map_create_map_point: "CREATE MAP POINT",
    map_del_btn: "DEL",
    map_no_entities_plotted: "NO PLOTTED ENTITIES FOUND",
    map_settlement_name: "Settlement Name",
    map_x_coord: "X COORD",
    map_z_coord: "Z COORD",
    map_copy_vector: "COPY VECTOR",
    map_zone_radius_label: "ZONE RADIUS",
    map_type_label: "TYPE",

    // Economy
    econ_import_btn: "📥 IMPORT FROM TYPES.XML",

    // Additional Dashboard / DB / Alerts keys
    status_save_all_btn: "SAVE ALL",
    status_discard_all_btn: "DISCARD ALL",
    db_clear_confirm: "Are you sure you want to clear the imported types.xml database?",
    db_no_tags: "No <type name=\"...\"> tags found in the uploaded XML file.",
    db_merge_confirm: "An existing items database is already loaded ({count} items).\n\nClick [OK] to MERGE (add new unique items and skip duplicates).\nClick [Cancel] to OVERWRITE (completely replace the current database with this file).",
    db_import_completed_merge: "Import Completed for {file}:\n- File parsed: {parsed} unique items ({internal} internal duplicates ignored).\n- Merged into database: +{merged} new unique items.\n- Ignored database duplicates: {dbDupes} items.\n- Consolidated database total: {total} items.",
    db_import_completed_overwrite: "Import Completed for {file}:\n- File parsed: {parsed} unique items ({internal} internal duplicates ignored).\n- Consolidated database total: {total} items.",
    db_parse_failed: "Failed to parse types.xml: {error}",
    toast_reverted: "Reverted field: {path}",
    toast_restore_success: "Successfully restored backup: {backup}",
    toast_restore_failed: "Restore failed: {error}",
    time_just_now: "Just now",
    time_min_ago: "{count} min ago",
    time_hours_ago: "{count} hours ago",
    time_days_ago: "{count} days ago",

    // Economy Editor
    econ_tab_categories: "📁 MARKET CATEGORIES ({count})",
    econ_tab_traders: "🤝 TRADER SETTINGS ({count})",
    econ_editing_cat: "EDITING:",
    econ_display_name: "DISPLAY NAME:",
    econ_init_stock: "INIT STOCK %:",
    econ_save_cat_btn: "SAVE CATEGORY",
    econ_filter_items: "FILTER ITEMS...",
    econ_filter_overrides: "FILTER OVERRIDES...",
    econ_search_all: "ALL CATS",
    econ_search_this: "THIS CAT",
    econ_add_item: "ADD ITEM:",
    econ_type_classname: "TYPE CLASSNAME...",
    econ_paste_btn: "📋 PASTE \"{classname}\"",
    econ_import_from_btn: "📥 IMPORT FROM…",
    econ_bulk_actions: "🛠 BULK ACTIONS:",
    econ_selected_count: "{count} SELECTED",
    econ_all_items: "ALL ITEMS",
    econ_bulk_op: "OPERATION:",
    econ_bulk_val: "VALUE:",
    econ_bulk_apply: "APPLY",
    econ_bulk_op_mult_buy: "Multiply Min & Max Price (Buy)",
    econ_bulk_op_mult_sell: "Multiply Sell Price %",
    econ_bulk_op_sync_sell: "Set Sell Price % (all items)",
    econ_bulk_confirm_title: "Apply Bulk Action",
    econ_bulk_confirm_body: "Apply bulk operation to {count} items?",
    econ_cross_found: "Found {count} result(s) across all categories for \"{query}\"",
    econ_th_classname: "CLASSNAME",
    econ_th_minprice: "MIN PRICE",
    econ_th_maxprice: "MAX PRICE",
    econ_th_minstock: "MIN STOCK",
    econ_th_maxstock: "MAX STOCK",
    econ_th_sellpct: "SELL %",
    econ_th_actions: "ACTIONS",
    econ_no_items_match: "NO ITEMS MATCHING FILTER",
    econ_no_items_add: "NO ITEMS. USE ADD ABOVE.",
    econ_select_cat: "SELECT CATEGORY FROM LIST",
    econ_select_trader: "SELECT TRADER CONFIG FROM LIST",
    econ_remove_item_title: "Remove Item",
    econ_remove_item_body: "Remove \"{classname}\" from the market list?",
    econ_toast_classname_exists: "Item classname already exists in this category!",
    econ_toast_added: "Added item: {classname}",
    econ_toast_removed: "Item removed.",
    econ_toast_copied: "Copied: {classname}",
    econ_toast_pasted: "Pasted: {classname}",
    econ_toast_already_exists: "\"{classname}\" already exists in this category.",
    econ_toast_import_same: "Cannot import from the same category.",
    econ_toast_import_empty: "Source category has no items.",
    econ_toast_import_exists: "All items from that category already exist here.",
    econ_import_confirm_title: "Import Items",
    econ_import_confirm_body: "Import {count} new item(s) from \"{category}\"?",
    econ_toast_imported: "Imported {count} items.",
    econ_toast_bulk_applied: "Bulk operation applied successfully.",
    econ_toast_bulk_invalid_val: "Enter a valid numeric value.",
    econ_toast_xml_no_select: "No items selected for import.",
    econ_toast_xml_price_error: "Min Price cannot be greater than Max Price.",
    econ_toast_xml_imported: "Imported {count} items to category.",
    
    // Trader settings UI strings
    trader_editing_data: "EDITING TRADER DATA:",
    trader_save_btn: "SAVE TRADER DATA",
    trader_general_params: "// GENERAL_TRADER_PARAMETERS",
    trader_currency_accepted: "// ACCEPTED_CURRENCIES",
    trader_market_categories: "// TRADER_MARKET_CATEGORIES",
    trader_item_overrides: "// INDIVIDUAL_ITEM_TRADE_OVERRIDES",
    trader_no_currencies: "NO CURRENCIES (FALLS BACK TO STANDARD BANKNOTE)",
    trader_add_currency: "ADD CURRENCY:",
    trader_search_class: "SEARCH CLASS...",
    trader_label_add_category: "ADD CATEGORY:",
    trader_add_category_btn: "[+] ADD CATEGORY",
    trader_add_override_btn: "ADD OVERRIDE:",
    trader_select_cat_ph: "-- SELECT CATEGORY --",
    trader_select_cat_override: "TRADE DIRECTION OVERRIDE",
    trader_currency_added: "Currency added: {classname}",
    trader_currency_removed: "Currency removed: {classname}",
    trader_cat_added: "Category added: {classname}",
    trader_cat_exists: "Category already added.",
    trader_toast_override_added: "Added override for {classname}",
    trader_th_category: "CATEGORY NAME",
    trader_th_override: "TRADE OVERRIDE",
    trader_th_action: "ACTION",
    trader_th_item: "ITEM CLASSNAME",
    trader_no_categories: "NO CATEGORIES ATTACHED.",
    trader_no_overrides: "NO CUSTOM OVERRIDES",
    trader_direction_both: "Buy & Sell (3)",
    trader_direction_buy: "Player Buy Only (1)",
    trader_direction_sell: "Player Sell Only (2)",
    trader_direction_disabled: "Disabled (0)",
    trader_label_name: "DISPLAY NAME",
    trader_label_icon: "TRADER ICON",
    trader_label_min_rep: "MIN REP REQUIREMENT",
    trader_label_max_rep: "MAX REP REQUIREMENT",
    trader_label_faction: "REQUIRED FACTION",
    trader_label_currency_name: "DISPLAY CURRENCY NAME",
    trader_label_quest_req: "COMPLETED QUEST REQ",
    trader_label_currency_val: "DISPLAY CURRENCY VALUE",
    trader_label_sort_order: "USE CATEGORY SORT ORDER",
    trader_quest_none: "None",
    trader_show_val: "Show (1)",
    trader_hide_val: "Hide (0)",
    trader_sort_standard: "Standard (0)",
    trader_sort_ascending: "Ascending (1)",
    
    // XML Import Modal
    xml_mass_import_title: "IMPORT FROM TYPES.XML",
    xml_target_cat: "Target Category: {category}",
    xml_missing_items: "Items missing from category: {count} (out of {total} total in types.xml database)",
    xml_set_defaults: "SET DEFAULT ITEM VALUES FOR IMPORTED ITEMS:",
    xml_search_missing: "SEARCH MISSING ITEMS...",
    xml_matches: "Matches: {count}",
    xml_select_all: "SELECT ALL FILTERED ({count})",
    xml_total_selected: "Total Selected: {count}",
    xml_no_missing_matches: "NO MISSING ITEMS MATCH YOUR SEARCH",
    xml_import_selected_btn: "📥 IMPORT SELECTED ({count})",

    // New additions (Economy search)
    econ_th_category: "CATEGORY",
    econ_th_goto: "GO TO",
    econ_cross_no_matches: "No matches.",

    // Map Sidebar & Coordinates
    map_layer_overlays: "LAYER OVERLAYS",
    map_ai_patrol_routing: "AI PATROL ROUTING",
    map_select_active_patrol: "SELECT ACTIVE PATROL",
    map_select_patrol_ph: "Select Patrol",
    map_draw_wp: "DRAW WAYPOINTS",
    map_draw_wp_active: "DRAW WAYPOINTS: ACTIVE",
    map_draw_wp_tip: "CLICK ON THE MAP TO ADD WAYPOINTS",
    map_clear_all_wp: "CLEAR ALL WAYPOINTS",
    map_search_placeholder: "SEARCH PLOTTED INDEX...",
    map_no_entities_found: "No entities found.",
    map_coordinate_inspector: "COORDINATE INSPECTOR",
    map_game_coordinates: "GAME COORDINATES",
    map_radius: "RADIUS",
    map_copy_to_profile: "COPY TO PROFILE",
    map_excluded_buildings: "EXCLUDED BUILDINGS",
    map_no_exclusions: "No exclusions.",
    map_exclude_placeholder: "Exclude building prefix...",
    map_add_btn: "ADD",
    map_spawn_modal_title: "PLOT NEW ENTITY",
    map_spawn_modal_type: "Entity Type",
    map_spawn_modal_name: "Entity Name",
    map_spawn_modal_npc_class: "NPC ClassName",
    map_spawn_modal_radius: "Zone Radius (meters)",
    map_spawn_modal_btn: "SPAWN",
    map_opt_airdrop: "AIRDROP MISSION",
    map_opt_npc: "NPC QUEST CHARACTER",
    map_opt_safezone: "SAFEZONE CIRCLE",
    map_opt_trader: "TRADER ZONE",
    map_opt_nogo: "NOGO AREA (AI BLOCK)",
    map_opt_roaming: "ROAMING LOCATION (SETTLEMENT)",

    // Settings Editor & Form
    settings_server_settings: "SERVER SETTINGS",
    settings_total: "TOTAL: {count} SCHEMAS",
    settings_select_config: "SELECT SETTINGS CONFIG FILE FROM LIST",
    config_reset: "RESET",
    config_delete: "DELETE",
    config_array_empty: "ARRAY IS EMPTY",
    config_show_on_map: "SHOW ON MAP",
    config_select_config: "SELECT CONFIGURATION FILE FROM SIDEBAR",
    config_parsing_error: "PARSING ERROR IN FILE",
    config_file_label: "FILE:",
    config_modified: "(MODIFIED ●)",
    config_size: "SIZE:",
    config_save: "● SAVE CONFIG",
    config_saved: "SAVED",
    config_export: "EXPORT FILE",
    config_reset_all: "RESET ALL",

    // AI Bots Editor
    ai_tab_patrol_manager: "PATROL MANAGER",
    ai_tab_loadout_designer: "LOADOUT DESIGNER",
    ai_tab_roaming_locations: "ROAMING LOCATIONS",
    ai_tab_loot_drops: "LOOT DROPS",
    ai_subtab_patrols: "PATROLS",
    ai_subtab_global_ai: "GLOBAL AI",
    ai_patrol_summary: "FACTION: {faction} · WAYPOINTS: {count}",
    ai_btn_create_patrol: "[+] CREATE NEW PATROL",
    ai_global_desc: "GLOBAL PARAMETERS SELECTED. USE THE CONFIGURATION PANELS ON THE RIGHT TO TWEAK VALUES.",

    // Quest Graph
    quest_flow_rep_faction: "FLOW, REPUTATION & FACTION",
    quest_prerequisites: "PREREQUISITE QUESTS",
    quest_add_prereq: "+ Add Prerequisite...",
    quest_followup: "FOLLOW-UP QUEST (NEXT)",
    quest_no_followup: "None (End of flow)",
    quest_details: "QUEST DETAILS",
    quest_objectives: "QUEST OBJECTIVES",
    quest_rewards: "QUEST REWARDS",
    quest_npc_giver: "SELECT QUEST GIVER NPC",
    quest_npc_turnin: "SELECT QUEST TURN-IN NPC",
    quest_objective_details: "OBJECTIVE DETAILS",
    quest_objective_text: "OBJECTIVE DIALOGUE TEXT",
    quest_time_limit: "TIME LIMIT (SECONDS)",

    // Quest Graph New Keys
    quest_btn_create: "[+] CREATE NEW QUEST",
    quest_editor_title: "QUEST_EDITOR",
    quest_delete_tooltip: "Delete quest config from disk",
    quest_btn_open_raw: "✎ OPEN RAW JSON",
    quest_flow_timeline: "OBJECTIVES FLOW TIMELINE",
    quest_edit_obj_tooltip: "Click to edit objective #{id}",
    quest_acc_general: "GENERAL DATA & DIALOGUES",
    quest_label_title: "QUEST TITLE",
    quest_label_summary: "OBJECTIVE SUMMARY TEXT",
    quest_label_start: "DIALOGUE: START QUEST",
    quest_label_progress: "DIALOGUE: IN PROGRESS",
    quest_label_completion: "DIALOGUE: COMPLETION",
    quest_chk_active: "Active",
    quest_chk_repeatable: "Repeatable",
    quest_chk_autocomplete: "Autocomplete",
    quest_chk_cancel_death: "Cancel on Death",
    quest_chk_group: "Group Quest",
    quest_chk_achievement: "Achievement",
    quest_acc_npcs: "QUEST GIVERS & TURN-INS NPCs",
    quest_label_givers: "QUEST GIVER NPCs:",
    quest_label_turnins: "QUEST TURN-IN NPCs:",
    quest_label_req_faction: "REQUIRED FACTION",
    quest_label_faction_reward: "FACTION REWARD",
    quest_label_rep_req: "REP REQUIREMENT",
    quest_label_rep_reward: "REP REWARD",
    quest_acc_items: "QUEST ITEMS & REWARDS",
    quest_label_items: "QUEST ITEMS:",
    quest_no_items: "NO ITEMS GRANTED FOR ACTIVE QUEST",
    quest_btn_add_item: "Add Item",
    quest_label_rewards: "REWARDS ON COMPLETION:",
    quest_no_rewards: "NO REWARDS CONFIGURED",
    quest_reward_chance: "CHANCE: {chance}%",
    quest_btn_add_reward: "+ Add Reward",
    quest_label_amount: "AMOUNT",
    quest_label_chance: "CHANCE (0.0-1.0)",
    quest_chk_must_select: "Player must select reward",
    quest_chk_random_reward: "Give random reward",
    quest_label_random_amount: "RANDOM REWARDS AMOUNT",
    quest_acc_objectives: "QUEST OBJECTIVES ({count})",
    quest_no_objectives: "NO OBJECTIVES ATTACHED. SELECT A TYPE BELOW TO INJECT.",
    quest_btn_edit: "EDIT",
    quest_btn_add: "[+] ADD",
    quest_modal_obj_details: "OBJECTIVE_DETAILS",
    quest_modal_obj_id: "Objective ID {id}",
    quest_chk_obj_active: "Objective Active",
    quest_label_coords: "LOCATION COORDINATES [X, Y, Z]",
    quest_btn_plot_map: "📌 PLOT ON MAP",
    quest_label_radius_m: "RADIUS (METERS)",
    quest_label_marker_name: "MARKER NAME",
    quest_chk_show_distance: "Show distance",
    quest_chk_trigger_enter: "Trigger enter",
    quest_chk_trigger_exit: "Trigger exit",
    quest_label_max_distance: "MAX DISTANCE",
    quest_label_req_collections: "REQUIRED COLLECTIONS:",
    quest_no_collections: "NO COLLECTION ITEMS ADDED",
    quest_label_kill_count: "KILL COUNT",
    quest_label_max_radial: "MAX RADIAL DISTANCE",
    quest_label_allowed_weapons: "ALLOWED WEAPONS (IF EMPTY, ANY WEAPON)",
    quest_btn_add_weapon: "Add Weapon",
    quest_btn_save_objective: "SAVE OBJECTIVE",
    quest_btn_close: "CLOSE",
    quest_obj_type_10: "Action",
    quest_obj_type_8: "AI Camp",
    quest_obj_type_7: "AI Patrol",
    quest_obj_type_9: "AI VIP Escort",
    quest_obj_type_4: "Collection",
    quest_obj_type_11: "Crafting",
    quest_obj_type_5: "Delivery",
    quest_obj_type_2: "Target (Kill)",
    quest_obj_type_3: "Travel",
    quest_obj_type_6: "Treasure Hunt",
    quest_ph_classname: "Type ClassName...",

    // AI Bots Editor New Keys
    ai_btn_save_patrol: "SAVE PATROL SETTINGS",
    ai_btn_create_patrol: "[+] CREATE NEW PATROL",
    ai_global_limits: "// GLOBAL SPAWN & DESPAWN LIMITS",
    ai_label_enable_patrols: "Enable Patrols",
    ai_opt_enabled: "1 - ENABLED",
    ai_opt_disabled: "0 - DISABLED",
    ai_label_spawn_min: "Spawn Distance Min (m)",
    ai_label_spawn_max: "Spawn Distance Max (m)",
    ai_label_despawn_radius: "Despawn Distance Radius (m)",
    ai_label_despawn_timeout: "AI Despawn Timeout (secs)",
    ai_label_respawn_cooldown: "AI Respawn Cooldown (secs)",
    ai_global_combat: "// GLOBAL COMBAT & THREAT PARAMETERS",
    ai_label_accuracy_min_ph: "Accuracy Min (-1 = use default)",
    ai_label_accuracy_max_ph: "Accuracy Max (-1 = use default)",
    ai_label_threat_distance: "Threat Distance Limit (m)",
    ai_label_noise_limit: "Noise Investigation Limit (m)",
    ai_label_flanking_distance: "Max Flanking Distance (m)",
    ai_label_enable_flanking_combat: "Enable Flanking Outside Combat",
    ai_opt_default: "-1 - Default",
    ai_label_damage_multiplier: "Damage Multiplier (Dealt)",
    ai_label_damage_received: "Damage Received Multiplier",
    ai_label_shoryuken_chance: "Shoryuken Melee Chance",
    ai_advanced_behaviors: "// ADVANCED AI CHARACTER BEHAVIORS (AISETTINGS.JSON)",
    ai_btn_save_behaviors: "SAVE GLOBAL AI BEHAVIORS",
    ai_movement_obstacles: "MOVEMENT & OBSTACLES",
    ai_label_vaulting: "ENABLE VAULTING (ПАРКУР БОТОВ):",
    ai_label_formation_scale: "FORMATION SCALE (МАСШТАБ СТРОЯ): {scale}",
    ai_melee_specials: "MELEE SPECIALS (SHORYUKEN)",
    ai_label_shoryuken_percent: "SHORYUKEN CHANCE (ВЕРОЯТНОСТЬ СУПЕРУДАРА): {chance}%",
    ai_label_shoryuken_damage_mult: "SHORYUKEN DAMAGE MULTIPLIER",
    ai_recruitment_mechanics: "RECRUITMENT MECHANICS (НАЙМ БОТОВ)",
    ai_label_recruit_friendly: "CAN RECRUIT FRIENDLY BOTS:",
    ai_opt_yes: "1 - YES",
    ai_opt_no: "0 - NO",
    ai_label_recruit_guards: "CAN RECRUIT GUARDS:",
    ai_label_max_recruitable: "MAX RECRUITABLE BOTS PER PLAYER",
    ai_threat_timeouts: "THREAT TIMEOUTS & CHAT",
    ai_label_combat_timeout: "COMBAT AGGRESSION TIMEOUT (SECS)",
    ai_label_guards_timeout: "GUARDS AGGRESSION TIMEOUT (SECS)",
    ai_patrol_properties: "// PATROL PROPERTIES",
    ai_btn_delete_patrol: "DELETE PATROL",
    ai_label_patrol_name: "Patrol Identifier Name",
    ai_label_loadout_profile: "Loadout Profile",
    ai_label_unit_min: "Unit Count (Min)",
    ai_label_unit_max: "Unit Count (Max)",
    ai_combat_targeting: "// COMBAT & TARGETING PARAMETERS (ПРИЦЕЛИВАНИЕ)",
    ai_label_accuracy_min_patrol: "Accuracy Min (-1 = use global)",
    ai_label_accuracy_max_patrol: "Accuracy Max (-1 = use global)",
    ai_label_enable_flanking: "Enable Flanking",
    ai_opt_use_global: "-1 - Use Global",
    ai_behavior_factions: "// BEHAVIOR, FACTIONS & DEATH LOOT",
    ai_label_faction: "AI Faction",
    ai_label_behavior_model: "AI Behavior Model",
    ai_label_patrol_speed: "Patrol Speed",
    ai_label_threat_speed: "Under Threat Speed",
    ai_label_default_stance: "Default Stance",
    ai_label_loot_drop_profile: "Loot Drop on Death Profile",
    ai_opt_none_default: "None (Use default)",
    ai_health_damage: "// HEALTH, DAMAGE MULTIPLIERS & AMMO",
    ai_label_headshot_resistance: "Headshot Resistance",
    ai_label_unlimited_reloads: "Unlimited Reloads (Mags count)",
    ai_label_lootable: "AI Lootable on Death",
    ai_opt_yes_looted: "Yes (Can be looted)",
    ai_opt_no_locked: "No (Inventory locked)",
    ai_custom_npc_units: "// CUSTOM NPC UNITS IN PATROL",
    ai_custom_npc_desc: "Specify the NPC types that spawn inside this patrol. If empty, standard bots spawn.",
    ai_custom_npc_empty: "Empty (Spawns default NPCs)",
    ai_label_add_unit: "ADD UNIT CLASS:",
    ai_ph_unit_class: "e.g. SurvivorM_Mirek",
    ai_patrol_waypoints: "// PATROL WAYPOINTS",
    ai_btn_plot_map: "🗺 PLOT ON MAP",
    ai_btn_add_waypoint: "[+] ADD WAYPOINT",
    ai_waypoints_empty: "No waypoints. AI remains static.",
    ai_patrols_none_detected: "NO PATROLS DETECTED. CLICK '+' ON THE LEFT PANEL TO CREATE A PATROL.",
    ai_bot_loadouts: "// BOT_LOADOUTS",
    ai_total_profiles: "TOTAL: {count} PROFILES",
    ai_btn_create_loadout: "[+] CREATE LOADOUT",
    ai_editing_loadout: "EDITING LOADOUT: ",
    ai_btn_save_loadout: "SAVE LOADOUT",
    ai_btn_clone_profile: "CLONE PROFILE",
    ai_btn_delete_file: "DELETE FILE",
    ai_clothing_slots: "CLOTHING SLOTS",
    ai_clothing_items_slot: "// CLOTHING ITEMS FOR SLOT: {slot}",
    ai_clothing_slot_empty: "No clothes assigned to this slot. The bot will spawn naked in this slot.",
    ai_label_chance: "Chance",
    ai_label_min_health: "Min Health",
    ai_label_max_health: "Max Health",
    ai_label_add_clothing: "ADD CLOTHING:",
    ai_ph_clothing_class: "Type clothing classname...",
    ai_inventory_cargo: "// BOT INVENTORY CARGO & WEAPONS (СНАРЯЖЕНИЕ / ЛУТ)",
    ai_inventory_cargo_empty: "Inventory is empty. No extra cargo/weapons spawned.",
    ai_label_spawn_chance: "Spawn Chance",
    ai_label_min_qty: "Min Qty",
    ai_label_max_qty: "Max Qty",
    ai_label_add_cargo: "ADD CARGO ITEM:",
    ai_ph_cargo_class: "Type weapon or item classname...",
    ai_select_loadout_sidebar: "SELECT LOADOUT PROFILE FROM SIDEBAR",
    ai_visual_roaming_title: "VISUAL ROAMING LOCATIONS EDITOR",
    ai_visual_roaming_desc: "Roaming locations, settlement centers, and spawn boundaries have been migrated completely to the Interactive Map tab. This allows you to drag settlements, resize spawn radii, and manage NoGo zones visually in real-time. Global building exclusions are also available in the map sidebar.",
    ai_btn_goto_map: "GO TO INTERACTIVE MAP",
    ai_loot_tables: "// AI_LOOT_TABLES",
    ai_total_loot_profiles: "TOTAL: {count} PROFILES",
    ai_btn_create_loot_profile: "[+] CREATE LOOT PROFILE",
    ai_editing_loot_profile: "EDITING PROFILE: ",
    ai_btn_save_loot_table: "SAVE LOOT TABLE",
    ai_btn_clone_loot_profile: "CLONE PROFILE",
    ai_btn_delete_loot_profile: "DELETE PROFILE",
    ai_loot_drops_index: "// LOOT DROPS INDEX ({count} ITEMS)",
    ai_loot_table_empty: "Loot table is empty. No drops configured for bots using this profile.",
    ai_label_drop_chance: "Drop Chance",
    ai_label_add_loot_item: "ADD ITEM TO LOOT DROP:",
    ai_ph_loot_item_class: "Type classname to drop...",
    ai_select_loot_sidebar: "SELECT LOOT PROFILE FROM SIDEBAR",
    ai_err_missing_config: "Error: AIPatrolSettings.json is missing or failed to parse.",
    ai_alert_min_patrol: "At least one patrol must remain in the configuration!",
    ai_confirm_delete_patrol: "Delete AI Patrol \"{name}\"?",
    ai_prompt_loadout_name: "Enter new Loadout profile name (e.g. MilBanditLoadout):",
    ai_alert_loadout_exists: "A loadout with this name already exists!",
    ai_confirm_delete_loadout: "Are you sure you want to delete loadout \"{name}\" from disk?",
    ai_prompt_clone_loadout: "Enter name for the cloned Loadout profile:",
    ai_confirm_delete_location: "Delete roaming location \"{name}\"?",
    ai_prompt_loot_name: "Enter new Loot Drop profile name (e.g. SoldierLoot):",
    ai_alert_loot_exists: "Loot Drop profile already exists!",
    ai_confirm_delete_loot: "Delete loot drop file: {path}?",
    ai_prompt_clone_loot: "Enter name for the cloned Loot Drop profile:",
    ai_alert_loot_item_exists: "Item classname already exists in this loot table!",
    ai_tooltip_item_missing: "Warning: This item classname is not found in the loaded types.xml database.",
    ai_tab_patrol_manager: "🚨 PATROL MANAGER",
    ai_tab_loadout_designer: "👕 LOADOUT DESIGNER",
    ai_tab_roaming_locations: "🗺 ROAMING LOCATIONS",
    ai_tab_loot_drops: "🎁 LOOT DROPS",
    ai_subtab_patrols: "PATROLS",
    ai_subtab_global: "GLOBAL AI",
    ai_msg_global_selected: "GLOBAL PARAMETERS SELECTED. USE THE CONFIGURATION PANELS ON THE RIGHT TO TWEAK VALUES.",
    ai_unsaved_changes: "(UNSAVED CHANGES ●)",
    ai_unsaved: "(UNSAVED ●)",

    // Sidebar
    sidebar_filter_configs: "// FILTER_CONFIGS",
    sidebar_search_ph: "ENTER SEARCH QUERY...",
    sidebar_total_files: "TOTAL: {count} FILES",
    sidebar_modified: "{count} MODIFIED",
    sidebar_no_matches: "NO CONFIGS MATCHING QUERY",

    // Global Search
    search_placeholder: "Search configs, items, quests, patrols...",
    search_no_results: "No results for \"{query}\"",
    search_categories_header: "SEARCHABLE CATEGORIES",
    search_shortcut_nav: "↑↓ navigate",
    search_shortcut_open: "↵ open",
    search_shortcut_toggle: "Ctrl+K toggle",
    search_hint_config: "📁 Config file paths",
    search_hint_market: "💰 Market item classnames",
    search_hint_quest: "📋 Quest titles & IDs",
    search_hint_patrol: "🤖 AI Patrol route names",
    search_hint_trader: "🛍 Trader display names",

    // Hotkey Modal
    hotkey_header_label: "// KEYBOARD_SHORTCUTS",
    hotkey_title: "HOTKEY CHEAT SHEET",
    hotkey_close: "× CLOSE",
    hotkey_section_global: "GLOBAL",
    hotkey_section_map: "TACTICAL MAP",
    hotkey_section_modals: "MODALS & DIALOGS",
    hotkey_key_search: "Open Global Search",
    hotkey_key_save: "Export / Save All modified files",
    hotkey_key_show_hotkeys: "Show this Hotkey Cheat Sheet",
    hotkey_key_delete: "Delete selected entity",
    hotkey_key_escape_entity: "Deselect current entity",
    hotkey_key_ruler: "Toggle Distance Ruler tool",
    hotkey_key_close_modal: "Close active modal / dialog",
    hotkey_key_confirm: "Confirm selected search result",
    hotkey_key_navigate: "Navigate search results",

    // Draft Recovery Modal
    draft_header_label: "// DRAFT_RECOVERY_SYSTEM",
    draft_title: "UNSAVED SESSION DRAFT FOUND",
    draft_body: "The editor found unsaved changes from a previous session ({count} modified files). Restore or discard?",
    draft_restore_btn: "Restore Draft",
    draft_discard_btn: "Discard",

    // Loading
    app_loading: "READING SERVER DIRECTORY...",

    // Error Boundary
    err_boundary_label: "// COMPONENT_ERROR_BOUNDARY",
    err_boundary_title: "PANEL RUNTIME ERROR",
    err_boundary_body: "This panel crashed unexpectedly. Your unsaved data is safe — all other tabs continue working normally.",
    err_boundary_retry: "↺ RETRY PANEL",
    err_boundary_hide_stack: "HIDE STACK TRACE",
    err_boundary_show_stack: "SHOW STACK TRACE",

    // Toast messages (App.jsx)
    toast_configs_loaded: "Configurations loaded from directory successfully!",
    toast_load_failed: "Failed to load configs: {error}",
    toast_write_denied: "Write permissions were not granted.",
    toast_select_failed: "Failed to select directory: {error}",
    toast_restore_denied: "Permission to write was denied.",
    toast_restore_access_failed: "Failed to restore access: {error}",
    toast_disconnected: "Disconnected configuration directory.",
    toast_draft_restored: "Draft restored: {count} files recovered.",
    toast_draft_discarded: "Draft discarded.",
    toast_file_saved: "Saved: {file}",
    toast_save_failed: "Save failed: {error}",
    toast_package_exported: "Package exported! {count} file(s) saved.",
    toast_export_failed: "Export failed: {error}",
    toast_no_modified: "No modified files to export.",
    toast_changes_discarded: "All unsaved changes discarded.",
    toast_file_created: "Created: {file}",
    toast_create_failed: "Create failed: {error}",
    toast_file_deleted: "Deleted: {file}",
    toast_delete_failed: "Delete failed: {error}",
    toast_syntax_repaired: "Syntax repaired: {file}",
    toast_repair_failed: "Repair failed: {error}",
    toast_autofix_done: "Auto-Fix complete! Repaired {syntax} syntax error(s) and {struct} structural warning(s).",

    // Confirm Modal defaults
    modal_cancel_default: "CANCEL",
    modal_confirm_default: "CONFIRM",

    // TacticalMap
    map_spawn_name_ph: "ENTER UNIQUE NAME...",
    map_coords_label: "COORDINATES",

    // Economy category stats
    econ_stats_items: "ITEMS",
    econ_stats_avg_min: "AVG MIN",
    econ_stats_avg_max: "AVG MAX",
    econ_stats_avg_sell: "AVG SELL",
    econ_editing_label: "EDITING:",
    econ_display_name_label: "DISPLAY NAME:",
    econ_init_stock_label: "INIT STOCK %:",
    econ_save_cat_btn_text: "SAVE CATEGORY",
    econ_filter_items_ph: "FILTER ITEMS...",
    econ_source_cat_label: "SOURCE CATEGORY:",
    econ_import_from_types: "📥 IMPORT FROM TYPES.XML",
    econ_bulk_apply_btn: "APPLY",
    econ_bulk_selected: "{count} SELECTED",
    econ_select_cat_label: "SELECT CATEGORY FROM LIST",
    econ_select_trader_label: "SELECT TRADER CONFIG FROM LIST",
    econ_trader_editing_label: "EDITING TRADER DATA:",
    econ_trader_save_btn: "SAVE TRADER DATA",
    xml_close_btn: "× CLOSE",

    // QuestGraph node port tooltips & misc
    quest_port_prereq: "Prerequisite Port",
    quest_port_followup: "Follow-up Port (Drag arrow to connect)",
    quest_locate_on_map: "Locate coordinates on the Tactical Map",
    quest_obj_file_missing: "Cannot edit objective file: failed to load or missing.",

    // AIBotsEditor cargo item tooltip (duplicate entry safety)
    ai_tooltip_cargo_missing: "Warning: This item classname is not found in the loaded types.xml database.",

    // EconomyEditor misc tooltips
    econ_translated_name_tooltip: "Translated Name",
    econ_search_all_categories_tooltip: "Search across all categories",
    econ_item_missing_tooltip: "Not found in types.xml database.",
    econ_copy_item_tooltip: "Copy item",
    econ_item_missing_trader_tooltip: "Not in types.xml"
  },
  ru: {
    // Welcome Screen
    welcome_title: "PROJECT ZERO TOOL",
    welcome_subtitle: "Полностью клиентский инструмент настройки DayZ Expansion. Редактируйте, проверяйте и управляйте конфигурациями серверов и картами локально в вашем браузере.",
    welcome_restore_btn: "📂 ВОССТАНОВИТЬ ДОСТУП К: {folder}",
    welcome_open_btn: "📂 ОТКРЫТЬ ЛОКАЛЬНУЮ ПАПКУ С МОДАМИ",
    welcome_open_diff_btn: "ОТКРЫТЬ ДРУГУЮ ПАПКУ",
    welcome_browser_warn_title: "⚠️ БРАУЗЕР НЕ ПОДДЕРЖИВАЕТСЯ",
    welcome_browser_warn_body: "Ваш текущий браузер не поддерживает File System Access API. Пожалуйста, используйте настольный браузер на движке Chromium (Google Chrome, Microsoft Edge, Opera или Brave) для редактирования файлов.",
    welcome_expected_struct: "ОЖИДАЕМАЯ СТРУКТУРА ПАПОК:",
    welcome_expected_desc: "Выберите папку профиля сервера DayZ, содержащую:",

    // Header & Tabs
    header_station: "EXPANSION // CONFIG_STATION",
    header_control_center: "PROJECT ZERO TOOL",
    header_dir: "ПАПКА:",
    header_disconnect: "× ОТКЛЮЧИТЬ",
    tab_dashboard: "Панель управления",
    tab_economy: "Экономика",
    tab_quests: "Квесты",
    tab_aibots: "ИИ Боты",
    tab_settings: "Настройки",
    tab_map: "Интерактивная карта",
    tab_raw_editor: "JSON",
    header_unsaved: "НЕ СОХРАНЕНО",
    header_export_package: "💾 ЭКСПОРТ ПАКЕТА",
    header_discard: "ОТКЛОНИТЬ",
    header_reload: "↻ ОБНОВИТЬ",
    header_shortcuts: "Горячие клавиши",
    all_saved: "✓ Все изменения сохранены",
    select_all: "Выбрать все",
    select_none: "Снять выделение",

    // Dashboard Tabs
    dash_sub_status: "СТАТУС СИСТЕМЫ",
    dash_sub_changelog: "ИЗМЕНЕНИЯ СЕССИИ",
    dash_sub_backups: "ПРОВОДНИК БЭКАПОВ",

    // Dashboard HUD Cards
    hud_quests: "Настроено квестов",
    hud_npcs: "Активные NPC",
    hud_market: "База данных магазина",
    hud_patrols: "Маршруты ИИ патрулей",
    hud_safezones: "Безопасные зоны",
    hud_total_configs: "Всего конфигураций",

    // Dashboard Status Panel
    status_pending_title: "// ОЖИДАЮЩИЕ_ИЗМЕНЕНИЯ",
    status_package_title: "СТАТУС ПАКЕТА КОНФИГОВ",
    status_match_disk: "ВСЕ КОНФИГУРАЦИОННЫЕ ФАЙЛЫ СОВПАДАЮТ С ДИСКОМ",
    status_size: "РАЗМЕР:",
    status_modified: "ИЗМЕНЕН",
    status_save_btn: "СОХРАНИТЬ",
    status_revert_btn: "ОТКАТИТЬ",

    // Dashboard Healing Panel
    status_diagnostics_title: "// АВТОИСПРАВЛЕНИЕ_И_ДИАГНОСТИКА",
    status_healing_title: "ВАЛИДАЦИЯ И ЛЕЧЕНИЕ",
    status_fix_all_btn: "🛠 АВТОИСПРАВЛЕНИЕ ВСЕХ ОШИБОК",
    status_healthy: "СИСТЕМА ЗДОРОВА: СИНТАКСИЧЕСКИХ И СТРУКТУРНЫХ ОШИБОК НЕ ОБНАРУЖЕНО",
    status_repair_syntax: "ИСПРАВИТЬ СИНТАКСИС",
    status_heal_btn: "ЛЕЧИТЬ",

    // Dashboard Database Panel
    db_title: "// БАЗА_ДАННЫХ_ПРЕДМЕТОВ_СЕРВЕРА",
    db_header: "БАЗА ПРЕДМЕТОВ СЕРВЕРА (TYPES.XML)",
    db_clear_btn: "ОЧИСТИТЬ БАЗУ",
    db_desc: "Загрузите файл types.xml вашего сервера DayZ (содержащий ванильные и модовые предметы), чтобы наполнить список автодополнения во всех редакторах (категории магазина, редактор снаряжения, спавн квестов и ботов).",
    db_choose_btn: "📁 ВЫБРАТЬ ФАЙЛ TYPES.XML",
    db_active_db: "✓ Активная база данных: {count} предметов загружено.",
    db_no_db: "База данных не загружена. Для автодополнения используются только локальные файлы.",

    // Dashboard Console
    console_title: "ЛОГИ КОНСОЛИ",
    console_init_ok: "[ИНИЦИАЛИЗАЦИЯ] УСПЕШНО · Загружено {count} конфигураций.",
    console_diagnostics_active: "[СЛУЖБА ДИСПЕТЧЕРА] Схемы успешно сопоставлены. Идет аудит...",
    console_warn_issues: "[ДИАГНОСТИКА] Предупреждение: Найдено {syntax} синтаксических ошибок и {struct} структурных предупреждений. Нажмите «АВТОИСПРАВЛЕНИЕ» для лечения.",
    console_status_green: "[ДИАГNOСТИКА] Статус системы зеленый: 0 синтаксических ошибок, 0 несоответствий схемам.",

    // Dashboard Changelog
    change_title: "// АУДИТ_ИЗМЕНЕНИЙ_СЕССИИ",
    change_header: "ЖУРНАЛ НЕСОХРАНЕННЫХ ИЗМЕНЕНИЙ",
    change_desc: "В этой вкладке показаны измененные свойства, которые сейчас хранятся только в оперативной памяти. Вы можете отменить конкретные изменения кнопкой «Undo».",
    change_no_changes: "НЕТ НЕСОХРАНЕННЫХ ИЗМЕНЕНИЙ В ТЕКУЩЕЙ СЕССИИ",
    change_th_path: "ПУТЬ К СВОЙСТВУ",
    change_th_orig: "ИСХОДНОЕ ЗНАЧЕНИЕ",
    change_th_mod: "ИЗМЕНЕННОЕ ЗНАЧЕНИЕ",
    change_th_action: "ДЕЙСТВИЕ",
    change_undo: "Отменить",

    // Dashboard Backups
    backup_title: "// АРХИВ_РЕЗЕРВНЫХ_КОПИЙ",
    backup_header: "ПРОВОДНИК БЭКАПОВ",
    backup_desc: "Восстанавливайте предыдущие версии конфигураций в один клик. Восстановление перезаписывает файлы на диске с запросом подтверждения.",
    backup_refresh: "↻ ОБНОВИТЬ",
    backup_refreshing: "ОБНОВЛЕНИЕ...",
    backup_loading: "ЗАГРУЗКА БЭКАПОВ С ДИСКА...",
    backup_no_points: "ТОЧЕК ВОССТАНОВЛЕНИЯ В ПАПКЕ БЭКАПОВ НЕ НАЙДЕНО",
    backup_full: "ПОЛНЫЙ ПАКЕТ",
    backup_single: "ОДИН ФАЙЛ",
    backup_files_in_archive: "Файлов в архиве: {count}",
    backup_show_files: "▶ ПОКАЗАТЬ СПИСОК ФАЙЛОВ",
    backup_hide_files: "▼ СКРЫТЬ СПИСОК ФАЙЛОВ",
    backup_restore_btn: "📂 ВОССТАНОВИТЬ",

    // Modals
    modal_confirm_restore_title: "ВОССТАНОВИТЬ БЭКАП",
    modal_confirm_restore_body: "Вы уверены, что хотите восстановить бэкап \"{backup}\"?\n\nЭто перезапишет все активные файлы на вашем диске файлами из этого архива.\n\nВсе несохраненные изменения в текущей сессии будут потеряны.",
    modal_confirm_discard_title: "ОТКЛОНИТЬ ВСЕ ИЗМЕНЕНИЯ",
    modal_confirm_discard_body: "Это вернет ВСЕ измененные конфигурации в памяти к их исходному состоянию на диске.\n\nЭто действие нельзя отменить.",
    modal_confirm_discard_btn: "ОТКЛОНИТЬ ВСЕ",
    modal_confirm_cancel: "ОТМЕНА",

    // Map Sidebar
    map_grid_presets: "// СЕТКА_И_МАСШТАБЫ",
    map_custom_size_label: "ШИРИНА КАРТЫ (В МЕТРАХ):",
    map_custom_size_opt: "Другой размер...",
    map_measure_btn: "ИЗМЕРИТЬ ДИСТАНЦИЮ",
    map_measure_on: "ИЗМЕРЕНИЕ: ВКЛ",
    map_load_custom: "🗺️ ЗАГРУЗИТЬ СВОЮ КАРТУ",
    map_merge_patrol_route: "ОБЪЕДИНИТЬ МАРШРУТЫ",
    map_merge_with: "Объединить с",
    map_merge_btn: "ОБЪЕДИНИТЬ",
    map_double_click_spawn: "ДВОЙНОЙ КЛИК: СОЗДАТЬ ОБЪЕКТ",
    map_inspect_selected: "ИНСПЕКТОР ВЫБРАННОГО",
    map_location_enabled: "Зона активна",
    map_more_settings: "ДОП. НАСТРОЙКИ",
    map_hovered_entity: "ВЫБРАТЬ ОБЪЕКТ (КЛИК)",
    map_spawn_new_entity: "СОЗДАТЬ НОВЫЙ ОБЪЕКТ",
    map_create_map_point: "СОЗДАТЬ ТОЧКУ КАРТЫ",
    map_del_btn: "УДАЛИТЬ",
    map_no_entities_plotted: "ОБЪЕКТЫ НА КАРТЕ НЕ НАЙДЕНЫ",
    map_settlement_name: "Название поселения",
    map_x_coord: "КООРДИНАТА X",
    map_z_coord: "КООРДИНАТА Z",
    map_copy_vector: "КОПИРОВАТЬ ВЕКТОР",
    map_zone_radius_label: "РАДИУС ЗОНЫ",
    map_type_label: "ТИП",

    // Economy
    econ_import_btn: "📥 ИМПОРТ ИЗ TYPES.XML",

    // Additional Dashboard / DB / Alerts keys
    status_save_all_btn: "СОХРАНИТЬ ВСЕ",
    status_discard_all_btn: "ОТКЛОНИТЬ ВСЕ",
    db_clear_confirm: "Вы уверены, что хотите очистить импортированную базу данных types.xml?",
    db_no_tags: "В загруженном файле XML не найдено тегов <type name=\"...\">.",
    db_merge_confirm: "Существующая база данных предметов уже загружена ({count} предметов).\n\nНажмите [OK] для СЛИЯНИЯ (добавить новые уникальные предметы и пропустить дубликаты).\nНажмите [Отмена] для ПЕРЕЗАПИСИ (полностью заменить текущую базу данных этим файлом).",
    db_import_completed_merge: "Импорт завершен для {file}:\n- Разобрано в файле: {parsed} уникальных предметов ({internal} внутренних дубликатов пропущено).\n- Объединено в базу: +{merged} новых уникальных предметов.\n- Пропущено дубликатов базы: {dbDupes} предметов.\n- Итоговый размер базы данных: {total} предметов.",
    db_import_completed_overwrite: "Импорт завершен для {file}:\n- Разобрано в файле: {parsed} уникальных предметов ({internal} внутренних дубликатов пропущено).\n- Итоговый размер базы данных: {total} предметов.",
    db_parse_failed: "Не удалось разобрать types.xml: {error}",
    toast_reverted: "Восстановлено поле: {path}",
    toast_restore_success: "Успешно восстановлен бэкап: {backup}",
    toast_restore_failed: "Ошибка восстановления: {error}",
    time_just_now: "Только что",
    time_min_ago: "{count} мин. назад",
    time_hours_ago: "{count} ч. назад",
    time_days_ago: "{count} дн. назад",

    // Economy Editor
    econ_tab_categories: "📁 КАТЕГОРИИ МАГАЗИНА ({count})",
    econ_tab_traders: "🤝 НАСТРОЙКИ ТОРГОВЦЕВ ({count})",
    econ_editing_cat: "РЕДАКТИРОВАНИЕ:",
    econ_display_name: "ОТОБРАЖАЕМОЕ ИМЯ:",
    econ_init_stock: "НАЧАЛЬНЫЙ ЗАПАС %:",
    econ_save_cat_btn: "СОХРАНИТЬ КАТЕГОРИЮ",
    econ_filter_items: "ФИЛЬТР ПРЕДМЕТОВ...",
    econ_filter_overrides: "ФИЛЬТР НАЦЕНОК...",
    econ_search_all: "ВСЕ КАТЕГОРИИ",
    econ_search_this: "ЭТА КАТЕГОРИЯ",
    econ_add_item: "ДОБАВИТЬ ПРЕДМЕТ:",
    econ_type_classname: "ВВЕДИТЕ CLASSNAME...",
    econ_paste_btn: "📋 ВСТАВИТЬ \"{classname}\"",
    econ_import_from_btn: "📥 ИМПОРТ ИЗ…",
    econ_bulk_actions: "🛠 ГРУППОВЫЕ ДЕЙСТВИЯ:",
    econ_selected_count: "ВЫДЕЛАНО: {count}",
    econ_all_items: "ВСЕ ПРЕДМЕТЫ",
    econ_bulk_op: "ОПЕРАЦИЯ:",
    econ_bulk_val: "ЗНАЧЕНИЕ:",
    econ_bulk_apply: "ПРИМЕНИТЬ",
    econ_bulk_op_mult_buy: "Умножить Мин. и Макс. цену (Покупка)",
    econ_bulk_op_mult_sell: "Умножить процент продажи %",
    econ_bulk_op_sync_sell: "Установить процент продажи % (всем)",
    econ_bulk_confirm_title: "Применить групповое действие",
    econ_bulk_confirm_body: "Применить групповую операцию к {count} предметам?",
    econ_cross_found: "Найдено {count} результатов во всех категориях для \"{query}\"",
    econ_th_classname: "КЛАСС ПРЕДМЕТА",
    econ_th_minprice: "МИН. ЦЕНА",
    econ_th_maxprice: "МАКС. ЦЕНА",
    econ_th_minstock: "МИН. ЗАПАС",
    econ_th_maxstock: "МАКС. ЗАПАС",
    econ_th_sellpct: "ПРОДАЖА %",
    econ_th_actions: "ДЕЙСТВИЯ",
    econ_no_items_match: "ПРЕДМЕТОВ С ТАКИМ ФИЛЬТРОМ НЕ НАЙДЕНО",
    econ_no_items_add: "НЕТ ПРЕДМЕТОВ. ИСПОЛЬЗУЙТЕ ДОБАВЛЕНИЕ ВЫШЕ.",
    econ_select_cat: "ВЫБЕРИТЕ КАТЕГОРИЮ ИЗ СПИСКА",
    econ_select_trader: "ВЫБЕРИТЕ ТОРГОВЦА ИЗ СПИСКА",
    econ_remove_item_title: "Удалить предмет",
    econ_remove_item_body: "Удалить \"{classname}\" из списка товаров?",
    econ_toast_classname_exists: "Предмет с таким classname уже есть в этой категории!",
    econ_toast_added: "Добавлен предмет: {classname}",
    econ_toast_removed: "Предмет удален.",
    econ_toast_copied: "Скопировано: {classname}",
    econ_toast_pasted: "Вставлено: {classname}",
    econ_toast_already_exists: "\"{classname}\" уже существует в этой категории.",
    econ_toast_import_same: "Невозможно импортировать из той же категории.",
    econ_toast_import_empty: "В исходной категории нет предметов.",
    econ_toast_import_exists: "Все предметы из этой категории уже есть здесь.",
    econ_import_confirm_title: "Импорт предметов",
    econ_import_confirm_body: "Импортировать {count} новых предметов из \"{category}\"?",
    econ_toast_imported: "Импортировано {count} предметов.",
    econ_toast_bulk_applied: "Групповая операция успешно применена.",
    econ_toast_bulk_invalid_val: "Введите корректное числовое значение.",
    econ_toast_xml_no_select: "Не выбрано ни одного предмета для импорта.",
    econ_toast_xml_price_error: "Минимальная цена не может быть больше максимальной.",
    econ_toast_xml_imported: "Импортировано {count} предметов в категорию.",
    
    // Trader settings UI strings
    trader_editing_data: "РЕДАКТИРОВАНИЕ ТОРГОВЦА:",
    trader_save_btn: "СОХРАНИТЬ ДАННЫЕ ТОРГОВЦА",
    trader_general_params: "// ОСНОВНЫЕ_ПАРАМЕТРЫ_ТОРГОВЦА",
    trader_currency_accepted: "// ПРИНИМАЕМАЯ_ВАЛЮТА",
    trader_market_categories: "// КАТЕГОРИИ_ТОВАРОВ_ТОРГОВЦА",
    trader_item_overrides: "// ИНДИВИДУАЛЬНЫЕ_НАЦЕНКИ_НА_ПРЕДМЕТЫ",
    trader_no_currencies: "НЕТ СОБСТВЕННОЙ ВАЛЮТЫ (ПО УМОЛЧАНИЮ ИСПОЛЬЗУЮТСЯ СТАНДАРТНЫЕ БАНКНОТЫ)",
    trader_add_currency: "ДОБАВИТЬ ВАЛЮТУ:",
    trader_search_class: "ПОИСК КЛАССА...",
    trader_label_add_category: "ДОБАВИТЬ КАТЕГОРИЮ:",
    trader_add_category_btn: "[+] ДОБАВИТЬ КАТЕГОРИЮ",
    trader_add_override_btn: "ДОБАВИТЬ НАЦЕНКУ:",
    trader_select_cat_ph: "-- ВЫБЕРИТЕ КАТЕГОРИЮ --",
    trader_select_cat_override: "НАПРАВЛЕНИЕ ТОРГОВЛИ",
    trader_currency_added: "Валюта добавлена: {classname}",
    trader_currency_removed: "Валюта удалена: {classname}",
    trader_cat_added: "Категория добавлена: {classname}",
    trader_cat_exists: "Категория уже добавлена торговцу.",
    trader_toast_override_added: "Добавлена индивидуальная наценка для {classname}",
    trader_th_category: "НАЗВАНИЕ КАТЕГОРИИ",
    trader_th_override: "ТОРГОВЫЙ РЕЖИМ",
    trader_th_action: "ДЕЙСТВИЕ",
    trader_th_item: "КЛАСС ПРЕДМЕТА",
    trader_no_categories: "НЕТ ПОДКЛЮЧЕННЫХ КАТЕГОРИЙ.",
    trader_no_overrides: "НЕТ ИНДИВИДУАЛЬНЫХ НАЦЕНОК",
    trader_direction_both: "Покупка и Продажа (3)",
    trader_direction_buy: "Только покупка игроком (1)",
    trader_direction_sell: "Только продажа игроком (2)",
    trader_direction_disabled: "Отключено (0)",
    trader_label_name: "ОТОБРАЖАЕМОЕ ИМЯ",
    trader_label_icon: "ИКОНКА ТОРГОВЦА",
    trader_label_min_rep: "МИН. РЕПУТАЦИЯ",
    trader_label_max_rep: "МАКС. РЕПУТАЦИЯ",
    trader_label_faction: "НЕОБХОДИМАЯ ФАКЦИЯ",
    trader_label_currency_name: "ИМЯ ОТОБРАЖАЕМОЙ ВАЛЮТЫ",
    trader_label_quest_req: "ТРЕБУЕМЫЙ КВЕСТ",
    trader_label_currency_val: "ПОКАЗЫВАТЬ ЦЕННОСТЬ ВАЛЮТЫ",
    trader_label_sort_order: "СОРТИРОВКА КАТЕГОРИЙ",
    trader_quest_none: "Нет",
    trader_show_val: "Показывать (1)",
    trader_hide_val: "Скрывать (0)",
    trader_sort_standard: "Стандартная (0)",
    trader_sort_ascending: "По возрастанию (1)",
    
    // XML Import Modal
    xml_mass_import_title: "ИМПОРТ ИЗ XML БАЗЫ ДАННЫХ",
    xml_target_cat: "Целевая категория: {category}",
    xml_missing_items: "Отсутствует предметов в категории: {count} (из {total} всего в базе types.xml)",
    xml_set_defaults: "НАСТРОЙКА ЗНАЧЕНИЙ ПО УМОЛЧАНИЮ ДЛЯ ИМПОРТА:",
    xml_search_missing: "ПОИСК ОТСУТСТВУЮЩИХ ПРЕДМЕТОВ...",
    xml_matches: "Совпадений: {count}",
    xml_select_all: "ВЫБРАТЬ ВСЕ ОТФИЛЬТРОВАННЫЕ ({count})",
    xml_total_selected: "Выбрано для импорта: {count}",
    xml_no_missing_matches: "ОТСУТСТВУЮЩИХ ПРЕДМЕТОВ С ТАКИМ ФИЛЬТРОМ НЕ НАЙДЕНО",
    xml_import_selected_btn: "📥 ИМПОРТИРОВАТЬ ВЫБРАННЫЕ ({count})",

    // New additions (Economy search)
    econ_th_category: "КАТЕГОРИЯ",
    econ_th_goto: "ПЕРЕЙТИ",
    econ_cross_no_matches: "Совпадений не найдено.",

    // Map Sidebar & Coordinates
    map_layer_overlays: "СЛОИ КАРТЫ",
    map_ai_patrol_routing: "МАРШРУТЫ ИИ ПАТРУЛЕЙ",
    map_select_active_patrol: "ВЫБЕРИТЕ АКТИВНЫЙ ПАТРУЛЬ",
    map_select_patrol_ph: "Выбрать патруль",
    map_draw_wp: "РИСОВАТЬ ТОЧКИ ПУТИ",
    map_draw_wp_active: "РИСОВАНИЕ ТОЧЕК: АКТИВНО",
    map_draw_wp_tip: "КЛИКНИТЕ НА КАРТУ, ЧТОБЫ ДОБАВИТЬ ТОЧКУ ПУТИ",
    map_clear_all_wp: "ОЧИСТИТЬ ВСЕ ТОЧКИ",
    map_search_placeholder: "ПОИСК ПО ИНДЕКСУ КАРТЫ...",
    map_no_entities_found: "Объекты не найдены.",
    map_coordinate_inspector: "ИНСПЕКТОР КООРДИНАТ",
    map_game_coordinates: "ИГРОВЫЕ КООРДИНАТЫ",
    map_radius: "РАДИУС",
    map_copy_to_profile: "КОПИРОВАТЬ В ПРОФИЛЬ",
    map_excluded_buildings: "ИСКЛЮЧЕННЫЕ ЗДАНИЯ",
    map_no_exclusions: "Исключений нет.",
    map_exclude_placeholder: "Префикс исключаемого здания...",
    map_add_btn: "ДОБАВИТЬ",
    map_spawn_modal_title: "РАЗМЕСТИТЬ НОВЫЙ ОБЪЕКТ",
    map_spawn_modal_type: "Тип объекта",
    map_spawn_modal_name: "Имя объекта",
    map_spawn_modal_npc_class: "Класснейм NPC",
    map_spawn_modal_radius: "Радиус зоны (в метрах)",
    map_spawn_modal_btn: "РАЗМЕСТИТЬ",
    map_opt_airdrop: "МИССИЯ СБРОСА ГРУЗА (AIRDROP)",
    map_opt_npc: "ПЕРСОНАЖ ДЛЯ КВЕСТА (NPC)",
    map_opt_safezone: "БЕЗОПАСНАЯ ЗОНА (SAFEZONE)",
    map_opt_trader: "ЗОНА ТОРГОВЦА (TRADER ZONE)",
    map_opt_nogo: "ЗОНА ЗАПРЕТА ИИ (NOGO AREA)",
    map_opt_roaming: "ТОЧКА БРОДЯЧИХ БОТОВ (ROAMING)",

    // Settings Editor & Form
    settings_server_settings: "НАСТРОЙКИ СЕРВЕРА",
    settings_total: "ВСЕГО: {count} СХЕМ",
    settings_select_config: "ВЫБЕРИТЕ КОНФИГ НАСТРОЕК ИЗ СПИСКА",
    config_reset: "СБРОСИТЬ",
    config_delete: "УДАЛИТЬ",
    config_array_empty: "МАССИВ ПУСТ",
    config_show_on_map: "ПОКАЗАТЬ НА КАРТЕ",
    config_select_config: "ВЫБЕРИТЕ ФАЙЛ КОНФИГУРАЦИИ В БОКОВОЙ ПАНЕЛИ",
    config_parsing_error: "ОШИБКА РАЗБОРА ФАЙЛА",
    config_file_label: "ФАЙЛ:",
    config_modified: "(ИЗМЕНЕНО ●)",
    config_size: "РАЗМЕР:",
    config_save: "● СОХРАНИТЬ КОНФИГ",
    config_saved: "СОХРАНЕНО",
    config_export: "ЭКСПОРТ ФАЙЛА",
    config_reset_all: "СБРОСИТЬ ВСЕ",

    // AI Bots Editor
    ai_tab_patrol_manager: "МЕНЕДЖЕР ПАТРУЛЕЙ",
    ai_tab_loadout_designer: "РЕДАКТОР СНАРЯЖЕНИЯ",
    ai_tab_roaming_locations: "БРОДЯЧИЕ ЗОНЫ",
    ai_tab_loot_drops: "СПАВН ЛУТА",
    ai_subtab_patrols: "ПАТРУЛИ",
    ai_subtab_global_ai: "ОБЩИЙ ИИ",
    ai_patrol_summary: "ФАКЦИЯ: {faction} · ТОЧЕК: {count}",
    ai_btn_create_patrol: "[+] СОЗДАТЬ НОВЫЙ ПАТРУЛЬ",
    ai_global_desc: "ВЫБРАНЫ ГЛОБАЛЬНЫЕ НАСТРОЙКИ. ИСПОЛЬЗУЙТЕ ПАНЕЛИ СПРАВА ДЛЯ ИЗМЕНЕНИЯ ЗНАЧЕНИЙ.",

    // Quest Graph
    quest_flow_rep_faction: "ПОСЛЕДОВАТЕЛЬНОСТЬ, РЕПУТАЦИЯ И ФАКЦИИ",
    quest_prerequisites: "ПРЕДВАРИТЕЛЬНЫЕ КВЕСТЫ",
    quest_add_prereq: "+ Добавить предв. квест...",
    quest_followup: "СЛЕДУЮЩИЙ КВЕСТ (ПОСЛЕДОВАТЕЛЬНЫЙ)",
    quest_no_followup: "Нет (Конец цепочки)",
    quest_details: "ДЕТАЛИ КВЕСТА",
    quest_objectives: "ЦЕЛИ КВЕСТА",
    quest_rewards: "НАГРАДЫ КВЕСТА",
    quest_npc_giver: "ВЫБЕРИТЕ NPC, ДАЮЩЕГО КВЕСТ",
    quest_npc_turnin: "ВЫБЕРИТЕ NPC ДЛЯ СДАЧИ КВЕСТА",
    quest_objective_details: "ДЕТАЛИ ЦЕЛИ",
    quest_objective_text: "ТЕКСТ ДИАЛОГА ЦЕЛИ",
    quest_time_limit: "ЛИМИТ ВРЕМЕНИ (В СЕКУНДАХ)",

    // Quest Graph New Keys
    quest_btn_create: "[+] СОЗДАТЬ НОВЫЙ КВЕСТ",
    quest_editor_title: "РЕДАКТОР КВЕСТОВ",
    quest_delete_tooltip: "Удалить конфигурацию квеста с диска",
    quest_btn_open_raw: "✎ ОТКРЫТЬ СЫРОЙ JSON",
    quest_flow_timeline: "ВРЕМЕННАЯ ШКАЛА ЦЕПОЧКИ ЦЕЛЕЙ",
    quest_edit_obj_tooltip: "Нажмите для редактирования цели #{id}",
    quest_acc_general: "ОСНОВНЫЕ ДАННЫЕ И ДИАЛОГИ",
    quest_label_title: "НАЗВАНИЕ КВЕСТА",
    quest_label_summary: "КРАТКОЕ ОПИСАНИЕ ЦЕЛИ",
    quest_label_start: "ДИАЛОГ: НАЧАЛО КВЕСТА",
    quest_label_progress: "ДИАЛОГ: В ПРОЦЕССЕ",
    quest_label_completion: "ДИАЛОГ: ЗАВЕРШЕНИЕ",
    quest_chk_active: "Активен",
    quest_chk_repeatable: "Повторяемый",
    quest_chk_autocomplete: "Автозавершение",
    quest_chk_cancel_death: "Отмена при смерти",
    quest_chk_group: "Групповой квест",
    quest_chk_achievement: "Достижение",
    quest_acc_npcs: "NPC ВЫДАЧИ И СДАЧИ КВЕСТОВ",
    quest_label_givers: "NPC, выдающие квест:",
    quest_label_turnins: "NPC для сдачи квеста:",
    quest_label_req_faction: "НЕОБХОДИМАЯ ФАКЦИЯ",
    quest_label_faction_reward: "НАГРАДА ФАКЦИИ",
    quest_label_rep_req: "ТРЕБУЕМАЯ РЕПУТАЦИЯ",
    quest_label_rep_reward: "НАГРАДА РЕПУТАЦИИ",
    quest_acc_items: "ПРЕДМЕТЫ И НАГРАДЫ КВЕСТА",
    quest_label_items: "ПРЕДМЕТЫ КВЕСТА:",
    quest_no_items: "ПРЕДМЕТЫ ДЛЯ АКТИВНОГО КВЕСТА НЕ НАЗНАЧЕНЫ",
    quest_btn_add_item: "Добавить предмет",
    quest_label_rewards: "НАГРАДЫ ЗА ВЫПОЛНЕНИЕ:",
    quest_no_rewards: "НАГРАДЫ НЕ НАСТРОЕНЫ",
    quest_reward_chance: "ШАНС: {chance}%",
    quest_btn_add_reward: "+ Добавить награду",
    quest_label_amount: "КОЛИЧЕСТВО",
    quest_label_chance: "ШАНС (0.0-1.0)",
    quest_chk_must_select: "Игрок должен выбрать награду",
    quest_chk_random_reward: "Выдать случайную награду",
    quest_label_random_amount: "КОЛИЧЕСТВО СЛУЧАЙНЫХ НАГРАД",
    quest_acc_objectives: "ЦЕЛИ КВЕСТА ({count})",
    quest_no_objectives: "НЕТ ПОДКЛЮЧЕННЫХ ЦЕЛЕЙ. ВЫБЕРИТЕ ТИП НИЖЕ ДЛЯ ДОБАВЛЕНИЯ.",
    quest_btn_edit: "РЕДАКТИРОВАТЬ",
    quest_btn_add: "[+] ДОБАВИТЬ",
    quest_modal_obj_details: "ДЕТАЛИ_ЦЕЛИ",
    quest_modal_obj_id: "Цель ID {id}",
    quest_chk_obj_active: "Цель активна",
    quest_label_coords: "КООРДИНАТЫ МЕСТОПОЛОЖЕНИЯ [X, Y, Z]",
    quest_btn_plot_map: "📌 ОТМЕТИТЬ НА КАРТЕ",
    quest_label_radius_m: "РАДИУС (В МЕТРАХ)",
    quest_label_marker_name: "ИМЯ МАРКЕРА",
    quest_chk_show_distance: "Показывать дистанцию",
    quest_chk_trigger_enter: "Триггер при входе",
    quest_chk_trigger_exit: "Триггер при выходе",
    quest_label_max_distance: "МАКСИМАЛЬНАЯ ДИСТАНЦИЯ",
    quest_label_req_collections: "НЕОБХОДИМЫЕ КОЛЛЕКЦИИ:",
    quest_no_collections: "ПРЕДМЕТЫ КОЛЛЕКЦИИ НЕ ДОБАВЛЕНЫ",
    quest_label_kill_count: "КОЛИЧЕСТВО УБИЙСТВ",
    quest_label_max_radial: "МАКС. РАДИАЛЬНАЯ ДИСТАНЦИЯ",
    quest_label_allowed_weapons: "РАЗРЕШЕННОЕ ОРУЖИЕ (ЕСЛИ ПУСТО - ЛЮБОЕ)",
    quest_btn_add_weapon: "Добавить оружие",
    quest_btn_save_objective: "СОХРАНИТЬ ЦЕЛЬ",
    quest_btn_close: "ЗАКРЫТЬ",
    quest_obj_type_10: "Действие",
    quest_obj_type_8: "Лагерь ИИ",
    quest_obj_type_7: "Патруль ИИ",
    quest_obj_type_9: "Сопровождение VIP ИИ",
    quest_obj_type_4: "Сбор",
    quest_obj_type_11: "Крафт",
    quest_obj_type_5: "Доставка",
    quest_obj_type_2: "Цель (Убийство)",
    quest_obj_type_3: "Путешествие",
    quest_obj_type_6: "Охота за сокровищами",
    quest_ph_classname: "Введите ClassName...",

    // AI Bots Editor New Keys
    ai_btn_save_patrol: "СОХРАНИТЬ НАСТРОЙКИ ПАТРУЛЯ",
    ai_btn_create_patrol: "[+] СОЗДАТЬ НОВЫЙ ПАТРУЛЬ",
    ai_global_limits: "// ГЛОБАЛЬНЫЕ ЛИМИТЫ СПАВНА И ДЕСПАВНА",
    ai_label_enable_patrols: "Включить патрули",
    ai_opt_enabled: "1 - ВКЛЮЧЕНО",
    ai_opt_disabled: "0 - ОТКЛЮЧЕНО",
    ai_label_spawn_min: "Мин. дистанция спавна (м)",
    ai_label_spawn_max: "Макс. дистанция спавна (м)",
    ai_label_despawn_radius: "Радиус дистанции деспавна (м)",
    ai_label_despawn_timeout: "Тайм-аут деспавна ИИ (сек)",
    ai_label_respawn_cooldown: "Перезарядка спавна ИИ (сек)",
    ai_global_combat: "// ГЛОБАЛЬНЫЕ ПАРАМЕТРЫ БОЯ И УГРОЗ",
    ai_label_accuracy_min_ph: "Мин. точность (-1 = по умолчанию)",
    ai_label_accuracy_max_ph: "Макс. точность (-1 = по умолчанию)",
    ai_label_threat_distance: "Лимит дистанции угрозы (м)",
    ai_label_noise_limit: "Лимит расследования шума (м)",
    ai_label_flanking_distance: "Макс. дистанция фланкирования (м)",
    ai_label_enable_flanking_combat: "Фланкирование вне боя",
    ai_opt_default: "-1 - По умолчанию",
    ai_label_damage_multiplier: "Множитель урона (наносимый)",
    ai_label_damage_received: "Множитель получаемого урона",
    ai_label_shoryuken_chance: "Шанс рукопашного суперудара",
    ai_advanced_behaviors: "// ДОПОЛНИТЕЛЬНОЕ ПОВЕДЕНИЕ ПЕРСОНАЖЕЙ ИИ (AISETTINGS.JSON)",
    ai_btn_save_behaviors: "СОХРАНИТЬ ПОВЕДЕНИЕ ИИ",
    ai_movement_obstacles: "ДВИЖЕНИЕ И ПРЕПЯТСТВИЯ",
    ai_label_vaulting: "РАЗРЕШИТЬ ПАРКУР (VAULTING):",
    ai_label_formation_scale: "МАСШТАБ СТРОЯ (FORMATION SCALE): {scale}",
    ai_melee_specials: "РУКОПАШНЫЕ СУПЕРАТАКИ (SHORYUKEN)",
    ai_label_shoryuken_percent: "ВЕРОЯТНОСТЬ СУПЕРУДАРА (SHORYUKEN): {chance}%",
    ai_label_shoryuken_damage_mult: "МНОЖИТЕЛЬ УРОНА СУПЕРУДАРА",
    ai_recruitment_mechanics: "МЕХАНИКА НАЙМА БОТОВ",
    ai_label_recruit_friendly: "МОЖНО НАНИМАТЬ ДРУЖЕСТВЕННЫХ БОТОВ:",
    ai_opt_yes: "1 - ДА",
    ai_opt_no: "0 - НЕТ",
    ai_label_recruit_guards: "МОЖНО НАНИМАТЬ ОХРАНУ:",
    ai_label_max_recruitable: "МАКСИМАЛЬНО НАНИМАЕМЫХ БОТОВ НА ИГРОКА",
    ai_threat_timeouts: "ТАЙМ-АУТЫ УГРОЗ И ЧАТ",
    ai_label_combat_timeout: "ТАЙМ-АУТ БОЕВОЙ АГРЕССИИ (СЕК)",
    ai_label_guards_timeout: "ТАЙМ-АУТ АГРЕССИИ ОХРАНЫ (СЕК)",
    ai_patrol_properties: "// СВОЙСТВА ПАТРУЛЯ",
    ai_btn_delete_patrol: "УДАЛИТЬ ПАТРУЛЬ",
    ai_label_patrol_name: "Идентификатор названия патруля",
    ai_label_loadout_profile: "Профиль снаряжения",
    ai_label_unit_min: "Количество ботов (Мин)",
    ai_label_unit_max: "Количество ботов (Макс)",
    ai_combat_targeting: "// ПАРАМЕТРЫ БОЯ И ПРИЦЕЛИВАНИЯ",
    ai_label_accuracy_min_patrol: "Мин. точность (-1 = глобальная)",
    ai_label_accuracy_max_patrol: "Макс. точность (-1 = глобальная)",
    ai_label_enable_flanking: "Включить фланкирование",
    ai_opt_use_global: "-1 - Глобальное значение",
    ai_behavior_factions: "// ПОВЕДЕНИЕ, ФАКЦИИ И ЛУТ ПОСЛЕ СМЕРТИ",
    ai_label_faction: "Фракция ИИ",
    ai_label_behavior_model: "Модель поведения ИИ",
    ai_label_patrol_speed: "Скорость патрулирования",
    ai_label_threat_speed: "Скорость при угрозе",
    ai_label_default_stance: "Поза по умолчанию",
    ai_label_loot_drop_profile: "Профиль выпадения лута при смерти",
    ai_opt_none_default: "Нет (По умолчанию)",
    ai_health_damage: "// ЗДОРОВЬЕ, МНОЖИТЕЛИ УРОНА И БОЕПРИПАСЫ",
    ai_label_headshot_resistance: "Сопротивление выстрелам в голову",
    ai_label_unlimited_reloads: "Бесконечные перезарядки (кол-во магазинов)",
    ai_label_lootable: "Разрешен сбор лута после смерти ИИ",
    ai_opt_yes_looted: "Да (Можно обыскивать)",
    ai_opt_no_locked: "Нет (Инвентарь заблокирован)",
    ai_custom_npc_units: "// ПОЛЬЗОВАТЕЛЬСКИЕ NPC В ПАТРУЛЕ",
    ai_custom_npc_desc: "Укажите типы NPC, которые спавнятся в этом патруле. Если пусто, спавнятся стандартные боты.",
    ai_custom_npc_empty: "Пусто (Спавнятся NPC по умолчанию)",
    ai_label_add_unit: "ДОБАВИТЬ КЛАСС ЮНИТА:",
    ai_ph_unit_class: "например, SurvivorM_Mirek",
    ai_patrol_waypoints: "// ТОЧКИ ПУТИ ПАТРУЛЯ",
    ai_btn_plot_map: "🗺 ПОКАЗАТЬ НА КАРТЕ",
    ai_btn_add_waypoint: "[+] ДОБАВИТЬ ТОЧКУ ПУТИ",
    ai_waypoints_empty: "Нет точек пути. ИИ стоит на месте.",
    ai_patrols_none_detected: "ПАТРУЛЕЙ НЕ ОБНАРУЖЕНО. НАЖМИТЕ «+» НА ЛЕВОЙ ПАНЕЛИ, ЧТОБЫ СОЗДАТЬ ПАТРУЛЬ.",
    ai_bot_loadouts: "// НАБОРЫ_СНАРЯЖЕНИЯ",
    ai_total_profiles: "ВСЕГО: {count} ПРОФИЛЕЙ",
    ai_btn_create_loadout: "[+] СОЗДАТЬ НАБОР СНАРЯЖЕНИЯ",
    ai_editing_loadout: "РЕДАКТИРОВАНИЕ НАБОРА: ",
    ai_btn_save_loadout: "СОХРАНИТЬ НАБОР",
    ai_btn_clone_profile: "КЛОНИРОВАТЬ ПРОФИЛЬ",
    ai_btn_delete_file: "УДАЛИТЬ ФАЙЛ",
    ai_clothing_slots: "СЛОТЫ ОДЕЖДЫ",
    ai_clothing_items_slot: "// ПРЕДМЕТЫ ОДЕЖДЫ ДЛЯ СЛОТА: {slot}",
    ai_clothing_slot_empty: "В этот слот не назначена одежда. Бот будет спавниться без нее.",
    ai_label_chance: "Шанс",
    ai_label_min_health: "Мин. здоровье",
    ai_label_max_health: "Макс. здоровье",
    ai_label_add_clothing: "ДОБАВИТЬ ОДЕЖДУ:",
    ai_ph_clothing_class: "Введите класс одежды...",
    ai_inventory_cargo: "// ИНВЕНТАРЬ КАРГО И ОРУЖИЕ БОТА",
    ai_inventory_cargo_empty: "Инвентарь пуст. Дополнительные предметы/оружие не спавнятся.",
    ai_label_spawn_chance: "Шанс спавна",
    ai_label_min_qty: "Мин. количество",
    ai_label_max_qty: "Макс. количество",
    ai_label_add_cargo: "ДОБАВИТЬ ПРЕДМЕТ ИНВЕНТАРЯ:",
    ai_ph_cargo_class: "Введите класс оружия или предмета...",
    ai_select_loadout_sidebar: "ВЫБЕРИТЕ ПРОФИЛЬ СНАРЯЖЕНИЯ В БОКОВОЙ ПАНЕЛИ",
    ai_visual_roaming_title: "ВИЗУАЛЬНЫЙ РЕДАКТОР ЗОН БРОДЯЧИХ БОТОВ",
    ai_visual_roaming_desc: "Зоны бродячих ботов, центры поселений и границы спавна полностью перенесены на вкладку «Интерактивная карта». Это позволяет перетаскивать поселения, изменять радиус спавна и управлять зонами запрета ИИ визуально в реальном времени. Исключения для зданий также доступны в боковой панели карты.",
    ai_btn_goto_map: "ПЕРЕЙТИ НА ИНТЕРАКТИВНУЮ КАРТУ",
    ai_loot_tables: "// ТАБЛИЦЫ_ВЫПАДЕНИЯ_ЛУТА",
    ai_total_loot_profiles: "ВСЕГО: {count} ПРОФИЛЕЙ",
    ai_btn_create_loot_profile: "[+] СОЗДАТЬ ТАБЛИЦУ ЛУТА",
    ai_editing_loot_profile: "РЕДАКТИРОВАНИЕ ТАБЛИЦЫ: ",
    ai_btn_save_loot_table: "СОХРАНИТЬ ТАБЛИЦУ ЛУТА",
    ai_btn_clone_loot_profile: "КЛОНИРОВАТЬ ТАБЛИЦУ",
    ai_btn_delete_loot_profile: "УДАЛИТЬ ТАБЛИЦУ",
    ai_loot_drops_index: "// СПИСОК ВЫПАДЕНИЯ ЛУТА ({count} ПРЕДМЕТОВ)",
    ai_loot_table_empty: "Таблица лута пуста. Выпадение лута для ботов с этим профилем не настроено.",
    ai_label_drop_chance: "Шанс выпадения",
    ai_label_add_loot_item: "ДОБАВИТЬ ПРЕДМЕТ В ВЫПАДЕНИЕ:",
    ai_ph_loot_item_class: "Введите класс выпадающего предмета...",
    ai_select_loot_sidebar: "ВЫБЕРИТЕ ПРОФИЛЬ ЛУТА В БОКОВОЙ ПАНЕЛИ",
    ai_err_missing_config: "Ошибка: файл AIPatrolSettings.json отсутствует или не может быть прочитан.",
    ai_alert_min_patrol: "В конфигурации должен оставаться как минимум один патруль!",
    ai_confirm_delete_patrol: "Удалить патруль ИИ \"{name}\"?",
    ai_prompt_loadout_name: "Введите название нового профиля снаряжения (например, MilBanditLoadout):",
    ai_alert_loadout_exists: "Профиль снаряжения с таким именем уже существует!",
    ai_confirm_delete_loadout: "Вы уверены, что хотите удалить профиль снаряжения \"{name}\" с диска?",
    ai_prompt_clone_loadout: "Введите имя для клонированного профиля снаряжения:",
    ai_confirm_delete_location: "Удалить зону бродячих ботов \"{name}\"?",
    ai_prompt_loot_name: "Введите имя нового профиля выпадения лута (например, SoldierLoot):",
    ai_alert_loot_exists: "Профиль выпадения лута уже существует!",
    ai_confirm_delete_loot: "Удалить файл выпадения лута: {path}?",
    ai_prompt_clone_loot: "Введите имя для клонированного профиля выпадения лута:",
    ai_alert_loot_item_exists: "Этот предмет уже добавлен в таблицу лута!",
    ai_tooltip_item_missing: "Предупреждение: этот предмет не найден в загруженной базе данных types.xml.",
    ai_tab_patrol_manager: "🚨 УПРАВЛЕНИЕ ПАТРУЛЯМИ",
    ai_tab_loadout_designer: "👕 КОНСТРУКТОР СНАРЯЖЕНИЯ",
    ai_tab_roaming_locations: "🗺 ЗОНЫ БРОДЯЧИХ БОТОВ",
    ai_tab_loot_drops: "🎁 ТАБЛИЦЫ ЛУТА",
    ai_subtab_patrols: "ПАТРУЛИ",
    ai_subtab_global: "ГЛОБАЛЬНЫЙ ИИ",
    ai_msg_global_selected: "ВЫБРАНЫ ГЛОБАЛЬНЫЕ ПАРАМЕТРЫ. ИСПОЛЬЗУЙТЕ ПАНЕЛИ НАСТРОЙКИ СПРАВА ДЛЯ ИЗМЕНЕНИЯ ЗНАЧЕНИЙ.",
    ai_unsaved_changes: "(НЕСОХРАНЕННЫЕ ИЗМЕНЕНИЯ ●)",
    ai_unsaved: "(НЕСОХРАНЕНО ●)",

    // Sidebar
    sidebar_filter_configs: "// ФИЛЬТР_КОНФИГОВ",
    sidebar_search_ph: "ВВЕДИТЕ ЗАПРОС ДЛЯ ПОИСКА...",
    sidebar_total_files: "ВСЕГО: {count} ФАЙЛОВ",
    sidebar_modified: "{count} ИЗМЕНЕНО",
    sidebar_no_matches: "КОНФИГОВ ПО ЗАПРОСУ НЕ НАЙДЕНО",

    // Global Search
    search_placeholder: "Поиск конфигов, предметов, квестов, патрулей...",
    search_no_results: "Ничего не найдено по запросу \"{query}\"",
    search_categories_header: "КАТЕГОРИИ ПОИСКА",
    search_shortcut_nav: "↑↓ навигация",
    search_shortcut_open: "↵ открыть",
    search_shortcut_toggle: "Ctrl+K переключить",
    search_hint_config: "📁 Пути к конфиг-файлам",
    search_hint_market: "💰 Классы предметов магазина",
    search_hint_quest: "📋 Названия и ID квестов",
    search_hint_patrol: "🤖 Маршруты ИИ патрулей",
    search_hint_trader: "🛍 Имена торговцев",

    // Hotkey Modal
    hotkey_header_label: "// ГОРЯЧИЕ_КЛАВИШИ",
    hotkey_title: "СПРАВКА ПО ГОРЯЧИМ КЛАВИШАМ",
    hotkey_close: "× ЗАКРЫТЬ",
    hotkey_section_global: "ГЛОБАЛЬНЫЕ",
    hotkey_section_map: "ТАКТИЧЕСКАЯ КАРТА",
    hotkey_section_modals: "МОДАЛЬНЫЕ ОКНА И ДИАЛОГИ",
    hotkey_key_search: "Открыть глобальный поиск",
    hotkey_key_save: "Экспорт / Сохранить все изменённые файлы",
    hotkey_key_show_hotkeys: "Показать эту справку по горячим клавишам",
    hotkey_key_delete: "Удалить выбранный объект",
    hotkey_key_escape_entity: "Снять выделение с объекта",
    hotkey_key_ruler: "Переключить инструмент измерения дистанции",
    hotkey_key_close_modal: "Закрыть активное модальное окно / диалог",
    hotkey_key_confirm: "Подтвердить выбранный результат поиска",
    hotkey_key_navigate: "Навигация по результатам поиска",

    // Draft Recovery Modal
    draft_header_label: "// СИСТЕМА_ВОССТАНОВЛЕНИЯ_ЧЕРНОВИКА",
    draft_title: "НАЙДЕН НЕСОХРАНЕННЫЙ ЧЕРНОВИК СЕССИИ",
    draft_body: "Редактор обнаружил несохраненные изменения из предыдущей сессии ({count} изменённых файлов). Восстановить или отклонить?",
    draft_restore_btn: "Восстановить черновик",
    draft_discard_btn: "Отклонить",

    // Loading
    app_loading: "ЧТЕНИЕ ДИРЕКТОРИИ СЕРВЕРА...",

    // Error Boundary
    err_boundary_label: "// ОШИБКА_КОМПОНЕНТА",
    err_boundary_title: "ОШИБКА ВЫПОЛНЕНИЯ ПАНЕЛИ",
    err_boundary_body: "Эта панель завершила работу с ошибкой. Несохраненные данные в безопасности — остальные вкладки продолжают работать нормально.",
    err_boundary_retry: "↺ ПЕРЕЗАПУСТИТЬ ПАНЕЛЬ",
    err_boundary_show_stack: "ПОКАЗАТЬ ТРАССИРОВКУ ОШИБКИ",
    err_boundary_hide_stack: "СКРЫТЬ ТРАССИРОВКУ ОШИБКИ",

    // Toast messages (App.jsx)
    toast_configs_loaded: "Конфигурации успешно загружены из директории!",
    toast_load_failed: "Ошибка загрузки конфигов: {error}",
    toast_write_denied: "Разрешение на запись не предоставлено.",
    toast_select_failed: "Ошибка выбора директории: {error}",
    toast_restore_denied: "Разрешение на запись отклонено.",
    toast_restore_access_failed: "Ошибка восстановления доступа: {error}",
    toast_disconnected: "Подключение к директории конфигов разорвано.",
    toast_draft_restored: "Черновик восстановлен: {count} файлов восстановлено.",
    toast_draft_discarded: "Черновик отклонён.",
    toast_file_saved: "Сохранено: {file}",
    toast_save_failed: "Ошибка сохранения: {error}",
    toast_package_exported: "Пакет экспортирован! Сохранено файлов: {count}.",
    toast_export_failed: "Ошибка экспорта: {error}",
    toast_no_modified: "Нет изменённых файлов для экспорта.",
    toast_changes_discarded: "Все несохраненные изменения отклонены.",
    toast_file_created: "Создан: {file}",
    toast_create_failed: "Ошибка создания: {error}",
    toast_file_deleted: "Удалён: {file}",
    toast_delete_failed: "Ошибка удаления: {error}",
    toast_syntax_repaired: "Синтаксис исправлен: {file}",
    toast_repair_failed: "Ошибка исправления: {error}",
    toast_autofix_done: "Автоисправление завершено! Исправлено синтаксических ошибок: {syntax}, структурных предупреждений: {struct}.",

    // Confirm Modal defaults
    modal_cancel_default: "ОТМЕНА",
    modal_confirm_default: "ПОДТВЕРДИТЬ",

    // TacticalMap
    map_spawn_name_ph: "ВВЕДИТЕ УНИКАЛЬНОЕ ИМЯ...",
    map_coords_label: "КООРДИНАТЫ",

    // Economy category stats
    econ_stats_items: "ПРЕДМЕТЫ",
    econ_stats_avg_min: "СРЕДН. МИН",
    econ_stats_avg_max: "СРЕДН. МАКС",
    econ_stats_avg_sell: "СРЕДН. ПРОДАЖА",
    econ_editing_label: "РЕДАКТИРОВАНИЕ:",
    econ_display_name_label: "ОТОБРАЖАЕМОЕ ИМЯ:",
    econ_init_stock_label: "НАЧАЛЬНЫЙ ЗАПАС %:",
    econ_save_cat_btn_text: "СОХРАНИТЬ КАТЕГОРИЮ",
    econ_filter_items_ph: "ФИЛЬТР ПРЕДМЕТОВ...",
    econ_source_cat_label: "ИСХОДНАЯ КАТЕГОРИЯ:",
    econ_import_from_types: "📥 ИМПОРТ ИЗ TYPES.XML",
    econ_bulk_apply_btn: "ПРИМЕНИТЬ",
    econ_bulk_selected: "ВЫБРАНО: {count}",
    econ_select_cat_label: "ВЫБЕРИТЕ КАТЕГОРИЮ ИЗ СПИСКА",
    econ_select_trader_label: "ВЫБЕРИТЕ ТОРГОВЦА ИЗ СПИСКА",
    econ_trader_editing_label: "РЕДАКТИРОВАНИЕ ТОРГОВЦА:",
    econ_trader_save_btn: "СОХРАНИТЬ ДАННЫЕ ТОРГОВЦА",
    xml_close_btn: "× ЗАКРЫТЬ",

    // QuestGraph node port tooltips & misc
    quest_port_prereq: "Порт предварительного квеста",
    quest_port_followup: "Порт следующего квеста (Перетащите стрелку для подключения)",
    quest_locate_on_map: "Найти координаты на Тактической карте",
    quest_obj_file_missing: "Невозможно редактировать файл цели: не удалось загрузить или файл отсутствует.",

    // AIBotsEditor cargo item tooltip
    ai_tooltip_cargo_missing: "Предупреждение: этот предмет не найден в загруженной базе данных types.xml.",

    // EconomyEditor misc tooltips
    econ_translated_name_tooltip: "Переведённое имя",
    econ_search_all_categories_tooltip: "Поиск по всем категориям",
    econ_item_missing_tooltip: "Не найдено в базе данных types.xml.",
    econ_copy_item_tooltip: "Копировать предмет",
    econ_item_missing_trader_tooltip: "Не найдено в types.xml"
  }
};
