const STR_KEY_MAP = {
  // Categories
  "#STR_EXPANSION_MARKET_CATEGORY_AMMO": "Ammo",
  "#STR_EXPANSION_MARKET_CATEGORY_AMMOBOXES": "Ammo Boxes",
  "#STR_EXPANSION_MARKET_CATEGORY_ARMBANDS": "Armbands",
  "#STR_EXPANSION_MARKET_CATEGORY_ASSAULT_RIFLES": "Assault Rifles",
  "#STR_EXPANSION_MARKET_CATEGORY_BACKPACKS": "Backpacks",
  "#STR_EXPANSION_MARKET_CATEGORY_BANDANAS": "Bandanas",
  "#STR_EXPANSION_MARKET_CATEGORY_BATTERIES": "Batteries",
  "#STR_EXPANSION_MARKET_CATEGORY_BAYONETS": "Bayonets",
  "#STR_EXPANSION_MARKET_CATEGORY_BELTS": "Belts",
  "#STR_EXPANSION_MARKET_CATEGORY_BLOUSES": "Blouses",
  "#STR_EXPANSION_MARKET_CATEGORY_SUITS": "Suits",
  "#STR_EXPANSION_MARKET_CATEGORY_BOATS": "Boats",
  "#STR_EXPANSION_MARKET_CATEGORY_BOOTS": "Boots",
  "#STR_EXPANSION_MARKET_CATEGORY_SHOES": "Shoes",
  "#STR_EXPANSION_MARKET_CATEGORY_BUTTSTOCKS": "Buttstocks",
  "#STR_EXPANSION_MARKET_CATEGORY_CAPS": "Caps",
  "#STR_EXPANSION_MARKET_CATEGORY_CARS": "Cars",
  "#STR_EXPANSION_MARKET_CATEGORY_COATS": "Coats",
  "#STR_EXPANSION_MARKET_CATEGORY_JACKETS": "Jackets",
  "#STR_EXPANSION_MARKET_CATEGORY_CONTAINERS": "Containers",
  "#STR_EXPANSION_MARKET_CATEGORY_CROSSBOWS": "Crossbows",
  "#STR_EXPANSION_MARKET_CATEGORY_DRINKS": "Drinks",
  "#STR_EXPANSION_MARKET_CATEGORY_ELECTRONICS": "Electronics",
  "#STR_EXPANSION_MARKET_CATEGORY_EVENT": "Event",
  "#STR_EXPANSION_MARKET_CATEGORY_EXCHANGE": "Exchange",
  "#STR_EXPANSION_MARKET_CATEGORY_EXPLOSIVES": "Explosives",
  "#STR_EXPANSION_MARKET_CATEGORY_GRENADES": "Grenades",
  "#STR_EXPANSION_MARKET_CATEGORY_EYEWEAR": "Eyewear",
  "#STR_EXPANSION_MARKET_CATEGORY_FISH": "Fish",
  "#STR_EXPANSION_MARKET_CATEGORY_FISHING": "Fishing",
  "#STR_EXPANSION_MARKET_CATEGORY_FLAGS": "Flags",
  "#STR_EXPANSION_MARKET_CATEGORY_FOOD": "Food",
  "#STR_EXPANSION_MARKET_CATEGORY_FRUIT_AND_VEGETABLES": "Fruit & Vegetables",
  "#STR_EXPANSION_MARKET_CATEGORY_FURNISHINGS": "Furnishings",
  "#STR_EXPANSION_MARKET_CATEGORY_GARDENING": "Gardening",
  "#STR_EXPANSION_MARKET_CATEGORY_GHILLIES": "Ghillies",
  "#STR_EXPANSION_MARKET_CATEGORY_GLOVES": "Gloves",
  "#STR_EXPANSION_MARKET_CATEGORY_HANDGUARDS": "Handguards",
  "#STR_EXPANSION_MARKET_CATEGORY_HATS": "Hats",
  "#STR_EXPANSION_MARKET_CATEGORY_HOODS": "Hoods",
  "#STR_EXPANSION_MARKET_CATEGORY_HELICOPTER": "Helicopters",
  "#STR_EXPANSION_MARKET_CATEGORY_HELMETS": "Helmets",
  "#STR_EXPANSION_MARKET_CATEGORY_HOLSTERS": "Holsters",
  "#STR_EXPANSION_MARKET_CATEGORY_KITS": "Kits",
  "#STR_EXPANSION_MARKET_CATEGORY_KNIFES": "Knives",
  "#STR_EXPANSION_MARKET_CATEGORY_LAUNCHERS": "Launchers",
  "#STR_EXPANSION_MARKET_CATEGORY_LIGHTS": "Lights",
  "#STR_EXPANSION_MARKET_CATEGORY_LIQUIDS": "Liquids",
  "#STR_EXPANSION_MARKET_CATEGORY_LOCKS": "Locks",
  "#STR_EXPANSION_MARKET_CATEGORY_MAGAZINES": "Magazines",
  "#STR_EXPANSION_MARKET_CATEGORY_MASKS": "Masks",
  "#STR_EXPANSION_MARKET_CATEGORY_MEAT": "Meat",
  "#STR_EXPANSION_MARKET_CATEGORY_MEDICALS": "Medicals",
  "#STR_EXPANSION_MARKET_CATEGORY_MEELE_WEAPONS": "Melee Weapons",
  "#STR_EXPANSION_MARKET_CATEGORY_MUZZLES": "Muzzles",
  "#STR_EXPANSION_MARKET_CATEGORY_NAVIGATION": "Navigation",
  "#STR_EXPANSION_MARKET_CATEGORY_OPTICS": "Optics",
  "#STR_EXPANSION_MARKET_CATEGORY_PANTS": "Pants",
  "#STR_EXPANSION_MARKET_CATEGORY_SHORTS": "Shorts",
  "#STR_EXPANSION_MARKET_CATEGORY_PISTOLS": "Pistols",
  "#STR_EXPANSION_MARKET_CATEGORY_RIFLES": "Rifles",
  "#STR_EXPANSION_MARKET_CATEGORY_SHIRTS": "Shirts",
  "#STR_EXPANSION_MARKET_CATEGORY_TSHIRTS": "T-Shirts",
  "#STR_EXPANSION_MARKET_CATEGORY_SHOTGUNS": "Shotguns",
  "#STR_EXPANSION_MARKET_CATEGORY_SKIRTS": "Skirts",
  "#STR_EXPANSION_MARKET_CATEGORY_DRESSES": "Dresses",
  "#STR_EXPANSION_MARKET_CATEGORY_SNIPER_RIFLES": "Sniper Rifles",
  "#STR_EXPANSION_MARKET_CATEGORY_SPRAYCANS": "Spraycans",
  "#STR_EXPANSION_MARKET_CATEGORY_SUBMACHINE_GUNS": "Submachine Guns",
  "#STR_EXPANSION_MARKET_CATEGORY_SUPPLIES": "Supplies",
  "#STR_EXPANSION_MARKET_CATEGORY_SWEATERS": "Sweaters",
  "#STR_EXPANSION_MARKET_CATEGORY_HOODIES": "Hoodies",
  "#STR_EXPANSION_MARKET_CATEGORY_TENTS": "Tents",
  "#STR_EXPANSION_MARKET_CATEGORY_TOOLS": "Tools",
  "#STR_EXPANSION_MARKET_CATEGORY_VEHICLE_PARTS": "Vehicle Parts",
  "#STR_EXPANSION_MARKET_CATEGORY_VESTS": "Vests",

  // Traders
  "#STR_EXPANSION_MARKET_TRADER_AIRCRAFT": "Aircraft",
  "#STR_EXPANSION_MARKET_TRADER_ATTACHMENTS": "Attachments",
  "#STR_EXPANSION_MARKET_TRADER_BOATS": "Boats",
  "#STR_EXPANSION_MARKET_TRADER_BUILDING_SUPPLIES": "Building Supplies",
  "#STR_EXPANSION_MARKET_TRADER_CLOTHING": "Clothing",
  "#STR_EXPANSION_MARKET_TRADER_CLOTHING_ACCESSORIES": "Clothing Accessories",
  "#STR_EXPANSION_MARKET_TRADER_COMPONENTS": "Components",
  "#STR_EXPANSION_MARKET_TRADER_CONSUMABLES": "Consumables",
  "#STR_EXPANSION_MARKET_TRADER_EVENT": "Event",
  "#STR_EXPANSION_MARKET_TRADER_EXCHANGE": "Exchange",
  "#STR_EXPANSION_MARKET_TRADER_FISHING": "Fishing",
  "#STR_EXPANSION_MARKET_TRADER_MEDICALS": "Medicals",
  "#STR_EXPANSION_MARKET_TRADER_SPECIAL": "Special",
  "#STR_EXPANSION_MARKET_TRADER_SPRAYCANS": "Spraycans",
  "#STR_EXPANSION_MARKET_TRADER_VEHICLE_PARTS": "Vehicle Parts",
  "#STR_EXPANSION_MARKET_TRADER_VEHICLES": "Vehicles",
  "#STR_EXPANSION_MARKET_TRADER_WEAPONS": "Weapons"
};

export function translateStrKey(str) {
  if (!str || typeof str !== 'string') return str || '';
  const trimmed = str.trim();
  if (!trimmed.startsWith('#STR_')) return trimmed;

  const key = trimmed.toUpperCase();
  if (STR_KEY_MAP[key]) return STR_KEY_MAP[key];

  // Compound keys check (e.g., "#STR_EXPANSION_MARKET_CATEGORY_BLOUSES & #STR_EXPANSION_MARKET_CATEGORY_SUITS")
  if (trimmed.includes('&')) {
    return trimmed
      .split('&')
      .map(part => translateStrKey(part.trim()))
      .join(' & ');
  }

  // Fallback: extract token, replace underscores with spaces, capitalize words
  const fallback = trimmed
    .replace(/^#STR_EXPANSION_MARKET_CATEGORY_/, '')
    .replace(/^#STR_EXPANSION_MARKET_TRADER_/, '')
    .replace(/^#STR_/, '')
    .replace(/_/g, ' ')
    .toLowerCase();

  return fallback.replace(/\b\w/g, c => c.toUpperCase());
}
